// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using VFi.NetDevPack.Utilities;

namespace VFi.Application.SO.DTOs
{
    public partial class SalesDiscountProductDto
    {
        public Guid? Id { get; set; }
        public Guid SalesDiscountId { get; set; }
        public Guid SalesOrderId { get; set; }
        public string SalesOrderCode { get; set; }
        public Guid? OrderProductId { get; set; }
        public Guid ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public double? Quantity { get; set; }
        public Guid? UnitId { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public Guid? GroupUnitId { get; set; }
        public string UnitType { get; set; }
        public decimal? UnitPrice { get; set; }
        public Guid? TaxCategoryId { get; set; }
        public double? TaxRate { get; set; }
        public string Tax { get; set; }
        public string ReasonDiscount { get; set; }
        public int? DisplayOrder { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? DiscountAmountDistribution { get; set; }
        public decimal? AmountDiscount { get; set; }
        public double? DiscountPercent { get; set; }
        public decimal? AmountNoDiscount
        {
            get
            {
                return (decimal)Quantity * UnitPrice;
            }
        }
        public decimal? TotalAmountDiscount
        {
            get
            {
                return (DiscountAmountDistribution ?? 0) + (AmountDiscount ?? 0);
            }
        }
        public decimal? AmountNoTax
        {
            get
            {
                return AmountNoDiscount - TotalAmountDiscount;
            }
        }
        public decimal? AmountTax
        {
            get
            {
                return AmountNoTax * (decimal)(TaxRate ?? 0) / 100;
            }
        }
        public decimal? TotalAmountTax
        {
            get
            {
                return AmountNoTax + AmountTax;
            }
        }
    }
}
