// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Application.SO.DTOs
{
    public partial class OrderExpressDto
    {
        public Guid? Id { get; set; }
        public string? OrderType { get; set; }
        public string? Code { get; set; }
        public DateTime? OrderDate { get; set; }
        public Guid? CustomerId { get; set; }
        public string? CustomerName { get; set; }
        public string? CustomerCode { get; set; }
        public Guid? StoreId { get; set; }
        public string? StoreCode { get; set; }
        public string? StoreName { get; set; }
        public Guid? ContractId { get; set; }
        public string? ContractName { get; set; }
        public string? Currency { get; set; }
        public decimal? ExchangeRate { get; set; }
        public Guid? ShippingMethodId { get; set; }
        public string? ShippingMethodCode { get; set; }
        public string? ShippingMethodName { get; set; }
        public string? RouterShipping { get; set; }
        public string? DomesticTracking { get; set; }
        public string? DomesticCarrier { get; set; }
        public int? Status { get; set; }
        public Guid? PaymentTermId { get; set; }
        public string? PaymentTermName { get; set; }
        public string? PaymentMethodName { get; set; }
        /// <summary>
        /// Điều khoản thanh toán
        /// </summary>
        public Guid? PaymentMethodId { get; set; }
        public int? PaymentStatus { get; set; }
        public string? ShipperName { get; set; }
        public string? ShipperPhone { get; set; }
        public string? ShipperZipCode { get; set; }
        public string? ShipperAddress { get; set; }
        public string? ShipperCountry { get; set; }
        public string? ShipperProvince { get; set; }
        public string? ShipperDistrict { get; set; }
        public string? ShipperWard { get; set; }
        public string? ShipperNote { get; set; }
        public string? DeliveryName { get; set; }
        public string? DeliveryPhone { get; set; }
        public string? DeliveryZipCode { get; set; }
        public string? DeliveryAddress { get; set; }
        public string? DeliveryCountry { get; set; }
        public string? DeliveryProvince { get; set; }
        public string? DeliveryDistrict { get; set; }
        public string? DeliveryWard { get; set; }
        public string? DeliveryNote { get; set; }
        public DateTime? EstimatedDeliveryDate { get; set; }
        public Guid? DeliveryMethodId { get; set; }
        public string? DeliveryMethodCode { get; set; }
        public string? DeliveryMethodName { get; set; }
        public int? DeliveryStatus { get; set; }
        public bool? IsBill { get; set; }
        public string? BillName { get; set; }
        public string? BillAddress { get; set; }
        public string? BillCountry { get; set; }
        public string? BillProvince { get; set; }
        public string? BillDistrict { get; set; }
        public string? BillWard { get; set; }
        public int? BillStatus { get; set; }
        public string? Description { get; set; }
        public string? Note { get; set; }
        public Guid? GroupEmployeeId { get; set; }
        public string? GroupEmployeeName { get; set; }
        public string? CommodityGroup { get; set; }
        public decimal? AirFreight { get; set; }
        public decimal? SeaFreight { get; set; }
        public decimal? Surcharge { get; set; }
        public int? Weight { get; set; }
        public int? Width { get; set; }
        public int? Height { get; set; }
        public int? Length { get; set; }
        public string? Image { get; set; }
        public decimal? Paid { get; set; }
        public decimal? Total { get; set; }
        public Guid? AccountId { get; set; }
        public string? AccountName { get; set; }
        public decimal? TotalProductAmount { get; set; }
        public decimal? TotalServiceAmount { get; set; }
        public decimal? TotalAmountCollected { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? CreatedByName { get; set; }
        public string? UpdatedByName { get; set; }
        public Guid? RouterShippingId { get; set; }
        //Mã gửi hàng
        public string? ShippingCodePost { get; set; }
        //Vận chuyển nội địa
        public string? TrackingCode { get; set; }
        //Hãng vận chuyện
        public string? TrackingCarrier { get; set; }
        public int? Package { get; set; }
        public DateTime? ToDeliveryDate { get; set; }
        public List<OrderExpressDetailDto> OrderExpressDetail { get; set; } = new List<OrderExpressDetailDto>();
        public List<OrderServiceAddDto>? OrderServiceAdd { get; set; }
        public List<PaymentInvoiceDto>? PaymentInvoice { get; set; }
        public List<OrderInvoiceDto>? OrderInvoice { get; set; }
        public List<OrderTrackingDto>? OrderTracking { get; set; }
    }
}
