// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace  VFi.Application.SO.DTOs
{
    public partial class PriceListCrossDetailDto
    {
        public Guid Id { get; set; }
        public Guid PriceListCrossId { get; set; }
        public string PriceListCross { get; set; }
        public string Note { get; set; }
        public Guid? CommodityGroupId { get; set; }
        public string CommodityGroupCode { get; set; }
        public string CommodityGroupName { get; set; }
        public decimal? AirFreight { get; set; }
        public decimal? SeaFreight { get; set; }
        public string Currency { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public int? Status { get; set; }
    }
}
