// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Application.SO.DTOs
{
    public class PriceListPurchaseDto
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public bool? Default { get; set; }
        public List<PriceListPurchaseDetailDto> Details { get; set; } = null!;

    }
    public class PriceListPurchaseParams
    {
        public int? Status { get; set; }
        public DateTime? Date { get; set; }
        public Guid? ProductId { get; set; }
        public double? Quantity { get; set; }
    }
    public class PriceListPurchaseListBoxDto
    {
        public Guid? Value { get; set; }
        public string Key { get; set; } = null!;
        public string Label { get; set; }
        public List<PriceListPurchaseDetailDto> Details { get; set; }
    }
}