// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.Domain.SO.Models;
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Application.SO.DTOs
{
    public partial class PriceListCrossDto
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public bool? Default { get; set; }
        public Guid? RouterShippingId { get; set; }
        public string RouterShipping { get; set; }
        public List<PriceListCrossDetailDto> Details { get; set; } = new List<PriceListCrossDetailDto>();

    }

    public class PriceListCrossListboxDto : ComboBoxDto
    {
        public Guid? RouterShippingId { get; set; }
        public int? Status { get; set; }
        public string RouterShipping { get; set; }

    }
}
