// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Application.SO.DTOs
{
    public partial class TopOrderDto
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public DateTime? OrderDate { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public decimal? Total { get; set; }
        public decimal? Paid { get; set; }
        public int? Status { get; set; }
        public int? PaymentStatus { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}
