// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Application.SO.DTOs
{
    public partial class TopPaymentDto
    {
        public Guid Id { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string OrderCode { get; set; }
        public string OrderExpressCode { get; set; }
        public string Description { get; set; }
        public decimal? Amount { get; set; }
        public string Currency { get; set; }
        public decimal? ExchangeRate { get; set; }
        public int? Status { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentCode { get; set; }
        public int? PaymentStatus { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? PaymentDate { get; set; }
    }
}
