// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace  VFi.Application.SO.DTOs
{
    public partial class WalletDto
    {
        public Guid Id { get; set; } 
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Cash { get; set; }
        public decimal CashHold { get; set; }
        public decimal CashHoldBid { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }
        public string Hash { get; set; }

        public decimal TotalCashHold => CashHold + CashHoldBid;
        public decimal CashAvailable => Cash - TotalCashHold;

    }
}
