// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace  VFi.Application.SO.DTOs
{
    public partial class WalletTransactionDto
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public Guid AccountId { get; set; }
        public Guid? WalletId { get; set; }
        /// <summary>
        /// DEPOSIT, PAY_ORDER, PAY, REFUND_FROM_CHARGE_ORDER
        /// </summary>
        public string Type { get; set; }
        public string Method { get; set; }
        public string Note { get; set; }
        public int Status { get; set; }
        public long? ParentId { get; set; }
        public DateTime? ApplyDate { get; set; }
        public string RawData { get; set; }
        public decimal? Balance { get; set; }
        public int? RefundStatus { get; set; }
        public decimal RefundAmount { get; set; }
        public DateTime? RefDate { get; set; }
        public Guid? RefId { get; set; }
        public string RefType { get; set; }
        public string RefCode { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string AuthorizationTransactionId { get; set; }
        public string AuthorizationTransactionCode { get; set; }
        public string AuthorizationTransactionResult { get; set; }
        public string CaptureTransactionId { get; set; }
        public string CaptureTransactionResult { get; set; }
        public string RefundTransactionId { get; set; }
        public string RefundTransactionResult { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }
         
    }
}
