// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class OrderFulfillmentDetailRequest : FilterQuery
    {
        public int? Status { get; set; }
    }
    public class AddOrderFulfillmentDetailRequest
    {
        public Guid OrderFulfillmentId { get; set; }
        public Guid ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string Origin { get; set; }
        public Guid? WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        /// <summary>
        /// Đơn giá
        /// </summary>
        public decimal? UnitPrice { get; set; }
        public string UnitName { get; set; }
        public int? Quantity { get; set; }
        public int? DisplayOrder { get; set; }
        public string Note { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
    }
    public class EditOrderFulfillmentDetailRequest : AddOrderFulfillmentDetailRequest
    {
        public Guid Id { get; set; }
    }
    
}