// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class OrderFulfillmentRequest : FilterQuery
    {
        public int? Status { get; set; }
    }
    public class AddOrderFulfillmentRequest
    {
        public int? OrderType { get; set; }
        public string Code { get; set; }
        public DateTime? OrderDate { get; set; }
        public Guid? CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Guid? StoreId { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public Guid? ContractId { get; set; }
        public string ContractName { get; set; }
        public Guid? ChannelId { get; set; }
        public string ChannelName { get; set; }
        public string ShipperName { get; set; }
        public string ShipperPhone { get; set; }
        public string ShipperZipCode { get; set; }
        public string ShipperAddress { get; set; }
        public string ShipperCountry { get; set; }
        public string ShipperProvince { get; set; }
        public string ShipperDistrict { get; set; }
        public string ShipperWard { get; set; }
        public string ShipperNote { get; set; }
        public int? PickupStatus { get; set; }
        public string PickupName { get; set; }
        public string PickupPhone { get; set; }
        public string PickupZipCode { get; set; }
        public string PickupAddress { get; set; }
        public string PickupCountry { get; set; }
        public string PickupProvince { get; set; }
        public string PickupDistrict { get; set; }
        public string PickupWard { get; set; }
        public string PickupNote { get; set; }
        public string AccountName { get; set; }
        public string Note { get; set; }
        public Guid? GroupEmployeeId { get; set; }
        public string GroupEmployeeName { get; set; }
        public Guid? AccountId { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
    }
    public class EditOrderFulfillmentRequest : AddOrderFulfillmentRequest
    {
        public Guid Id { get; set; }
    }
    
}