// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class OrderExpressDetailPagingRequest : FilterQuery
    {
        public int? Status { get; set; }
    }

    public class AddOrderExpressDetailRequest
    {
        public Guid OrderExpressId { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string Origin { get; set; }
        public string UnitName { get; set; }
        public int? Quantity { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? DisplayOrder { get; set; }
        public string Note { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public string CommodityGroup { get; set; }
        public string SurchargeGroup { get; set; }
        public decimal? Surcharge { get; set; }
    }
    public class EditOrderExpressDetailRequest : AddOrderExpressDetailRequest
    {
        public Guid Id { get; set; }
    }
    
}