// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class PostOfficeRequest : FilterQuery
    {
        public int? Status { get; set; }
    }
    public class AddPostOfficeRequest
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string SyntaxSender { get; set; }
        public string Note { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
    }
    public class EditPostOfficeRequest : AddPostOfficeRequest
    {
        public Guid Id { get; set; }
    }
  
}