// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class PriceListCrossFilterQueryRequest : FilterQuery
    {
    }
    public class PriceListCrossByAccountFilterQueryRequest : FilterQuery
    {
        [FromQuery(Name = "$accountId")]
        public Guid AccountId { get; set; }

        [FromQuery(Name = "$routerShippingId")]
        public Guid? RouterShippingId { get; set; }
    }
    public class PriceListCrossRequest
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public int? DisplayOrder { get; set; }
        public bool? Default { get; set; }
        public Guid? RouterShippingId { get; set; }
        public string RouterShipping { get; set; }
        public List<EditPriceListCrossDetailRequest> Details { get; set; } = new List<EditPriceListCrossDetailRequest>();
    }

    public class PriceListCrossListBoxRequest : ComboBoxRequest
    {
        [FromQuery(Name = "$routerShippingId")]
        public Guid? RouterShippingId { get; set; }
    }
}
