// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class PriceListSurchargeFilterQueryRequest : FilterQuery
    {
    }

    public class PriceListSurchargeRequest
    {
        public string Note { get; set; }
        public Guid RouterShippingId { get; set; }
        public string RouterShipping { get; set; }
        public Guid? SurchargeGroupId { get; set; }
        public string SurchargeGroup { get; set; }
        public decimal? Price { get; set; }
        public string Currency { get; set; }
        public int? Status { get; set; }
    }

    public class AddPriceListSurchargeRequest
    {
        public Guid RouterShippingId { get; set; }
        public string RouterShipping { get; set; }
        public List<PriceListSurchargeRequest> Details { get; set; }
    }



    public class EditPriceListSurchargeRequest : PriceListSurchargeRequest
    {
    }
    public class PriceListSurchargeListBoxRequest : ComboBoxRequest
    {
        [FromQuery(Name = "$routerShippingId")]
        public Guid? RouterShippingId { get; set; }
    }
}
