// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class PriceListPurchaseDetailRequest : FilterQuery
    {
        public int? Status { get; set; }
    }
    public class AddPriceListPurchaseDetailRequest
    {
        public Guid? PurchaseGroupId { get; set; }
        public string PurchaseGroupCode { get; set; }
        public string PurchaseGroupName { get; set; }
        public string Note { get; set; }
        public int? BuyFee { get; set; }
        public decimal? BuyFeeMin { get; set; }
        public string Currency { get; set; }
        public int? Status { get; set; }
        public int? DisplayOrder { get; set; }
        public decimal? BuyFeeFix { get; set; }
    }
    public class EditPriceListPurchaseDetailRequest : AddPriceListPurchaseDetailRequest
    {
        public Guid? Id { get; set; }
    }
     
}
