// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class TransactionRequest : FilterQuery
    {
        public int? Status { get; set; }
    }
    public class AddTransactionRequest
    {
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public string AccountId { get; set; }
        public string WalletId { get; set; }
        /// <summary>
        /// DEPOSIT, PAY_ORDER, PAY, REFUND_FROM_CHARGE_ORDER
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// 1,2,3
        /// </summary>
        public string ObjectRef { get; set; }
        /// <summary>
        /// 1,2,3
        /// </summary>
        public string AuthorizeRef { get; set; }
        public string TransactionRef { get; set; }
        public string Source { get; set; }
        public string MetaData { get; set; }
        public int Status { get; set; }
        public long? ParentId { get; set; }
        public DateTime? ApplyDate { get; set; }
        public string RawData { get; set; }
        public string Currency { get; set; }
        public string AuthorizationTransactionId { get; set; }
        public string AuthorizationTransactionCode { get; set; }
        public string AuthorizationTransactionResult { get; set; }
        public string CaptureTransactionId { get; set; }
        public string CaptureTransactionResult { get; set; }
        public string RefundTransactionId { get; set; }
        public string RefundTransactionResult { get; set; }
        public DateTime? TransactionDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }
    }
    public class EditTransactionRequest : AddTransactionRequest
    {
        public Guid Id { get; set; }
    }
  
}
