// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Api.SO.ViewModels
{
    public class WalletRequest : FilterQuery
    {
        public int? Status { get; set; }
    }
    public class AddWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal? Cash { get; set; }
        public decimal? CashHold { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }
    }
    public class EditWalletRequest : AddWalletRequest
    {
        public Guid Id { get; set; }
    }
    public class DepositWalletRequest
    { 
        public string CustomerCode { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentNote { get; set; }
        public DateTime PaymentDate { get; set; }
        public string Document { get; set; } 
    }
    public class DepositFromBankRequest
    {
        public string CustomerCode { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentNote { get; set; }
        public DateTime PaymentDate { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string BankNumber { get; set; }
    }
    public class WithdrawWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; } 
        public string Method { get; set; }//BANK, MONEY
        public string Note { get; set; }
        public string RawData { get; set; } 
        public DateTime RefDate { get; set; }
        public Guid? RefId { get; set; }
    }
    public class PayWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; } 
        public string Note { get; set; }
        public string RawData { get; set; }
        public DateTime? RefDate { get; set; }
    }
    public class RefundPayWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public string RawData { get; set; }
        public DateTime? RefDate { get; set; }
        public Guid? RefId { get; set; }
    }
    public class PayOrderWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public string RawData { get; set; } 
        public string OrderCode { get; set; }
        public Guid OrderId { get; set; }
    }
    public class RefundOrderWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public string RawData { get; set; }
        public string OrderCode { get; set; }
        public Guid OrderId { get; set; }
        public Guid? RefId { get; set; }
    }



    public class HoldWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public string RawData { get; set; }
        public DateTime RefDate { get; set; }
    }
    public class RefundHoldWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public string RawData { get; set; }
        public DateTime RefDate { get; set; }
        public Guid? RefId { get; set; }
    }

    public class HoldBidWalletRequest
    {
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public DateTime RefDate { get; set; }
    }
    public class RefundHoldBidWalletRequest
    {
        public Guid AccountId { get; set; }
        public Guid? RefId { get; set; }
        public string Note { get; set; }
    }
}
