// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    /// <summary>
    /// Danh mục ngân hàng
    /// </summary>
    public partial class Bank : Entity, IAggregateRoot
    {
     
        /// <summary>
        /// Mã ngân hàng (tên viết tắt)
        /// </summary>
        public string Code { get; set; }
        public string Qrbin { get; set; }
        public string ShortName { get; set; }
        /// <summary>
        /// Tên ngân hàng (tên đầy đủ)
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Tên tiếng anh
        /// </summary>
        public string EnglishName { get; set; }
        /// <summary>
        /// Địa chỉ (trụ sở chính)
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// Thứ tự hiển thị trong danh sách
        /// </summary>
        public int DisplayOrder { get; set; }
        /// <summary>
        /// Trạng thái. = 0 - Ngừng sử dụng, = 1 - Đang sử dụng
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// Ghi chú/Diễn giải.
        /// </summary>
        public string Note { get; set; }
        /// <summary>
        /// Ảnh
        /// </summary>
        public string Image { get; set; }
        public Guid? CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        /// <summary>
        /// Ngày giờ tạo
        /// </summary>
        public DateTime? CreatedDate { get; set; }
        /// <summary>
        /// Ngày giờ sửa
        /// </summary>
        public DateTime? UpdatedDate { get; set; }
    }
}