// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class Campaign : Entity, IAggregateRoot
    {
        public Guid Id { get; set; }

        public string Code { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? EndDate { get; set; }

        public Guid? Leader { get; set; }

        public string LeaderName { get; set; }

        public string Member { get; set; }

        public int? Status { get; set; }

        public Guid? CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public Guid? UpdatedBy { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string CreatedByName { get; set; }

        public string UpdatedByName { get; set; }

        [NotMapped]
        public int? LeadCount { get; set; }
        public virtual ICollection<CampaignStatus> CampaignStatuses { get; set; } = new List<CampaignStatus>();

        public virtual ICollection<LeadCampaign> LeadCampaigns { get; set; } = new List<LeadCampaign>();
    }
}
