// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Coupon : Entity, IAggregateRoot
    {
        public Coupon()
        {
            CouponCustomer = new HashSet<CouponCustomer>();
            CouponCustomerGroup = new HashSet<CouponCustomerGroup>();
        }

     
        public Guid? CouponGroupId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public string Stores { get; set; }
        public string SalesChannel { get; set; }
        public bool? ApplyTogether { get; set; }

        public  CouponGroup CouponGroup { get; set; }
        public  ICollection<CouponCustomer> CouponCustomer { get; set; }
        public  ICollection<CouponCustomerGroup> CouponCustomerGroup { get; set; }
    }
}