// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class CouponCustomer : Entity, IAggregateRoot
    {

        public Guid? CouponId { get; set; }
        public Guid? CustomerId { get; set; }

        public  Coupon Coupon { get; set; }
        public  Customer Customer { get; set; }
    }
}