// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class CustomerAddress : Entity, IAggregateRoot
    {
        public CustomerAddress()
        {
            SalesDiscount = new HashSet<SalesDiscount>();
        }
        public Guid? CustomerId { get; set; }
        public Guid? EmployeeId { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        /// <summary>
        /// Địa chỉ giao hàng mặc định
        /// </summary>
        public bool? ShippingDefault { get; set; }
        /// <summary>
        /// Địa chỉ xuất hóa đơn mặc định
        /// </summary>
        public bool? BillingDefault { get; set; }
        public string Note { get; set; }
        public int? Status { get; set; }
        public int? SortOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SalesDiscount> SalesDiscount { get; set; }
    }
}