// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Customer : Entity, IAggregateRoot
    {
        public Customer()
        {
            CouponCustomer = new HashSet<CouponCustomer>();
            CustomerAddress = new HashSet<CustomerAddress>();
            CustomerBank = new HashSet<CustomerBank>();
            CustomerBusinessMapping = new HashSet<CustomerBusinessMapping>();
            CustomerContact = new HashSet<CustomerContact>();
            CustomerGroupMapping = new HashSet<CustomerGroupMapping>();
            CustomerPriceListCross = new HashSet<CustomerPriceListCross>();
            CustomerProfile = new HashSet<CustomerProfile>();
            Order = new HashSet<Order>();
            PromotionCustomer = new HashSet<PromotionCustomer>();
            ReturnOrder = new HashSet<ReturnOrder>();
            SalesDiscount = new HashSet<SalesDiscount>();
        }

        public Guid? CustomerSourceId { get; set; }
        public string CustomerSourceName { get; set; }
        public string Image { get; set; }
        public int? Type { get; set; }
        public string Code { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string TaxCode { get; set; }
        public string BusinessSector { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyName { get; set; }
        public string CompanySize { get; set; }
        public decimal? Capital { get; set; }
        public DateTime? EstablishedDate { get; set; }
        public string Tags { get; set; }
        public string Note { get; set; }
        public int? Status { get; set; }
        public Guid? EmployeeId { get; set; }
        public Guid? GroupEmployeeId { get; set; }
        public bool? IsVendor { get; set; }
        public int? Gender { get; set; }
        public int? Year { get; set; }
        public int? Month { get; set; }
        public int? Day { get; set; }
        public Guid? CurrencyId { get; set; }
        public string Currency { get; set; }
        public string CurrencyName { get; set; }
        public Guid? PriceListId { get; set; }
        public string PriceListName { get; set; }
        public Guid? PriceListPurchaseId { get; set; }
        public string PriceListPurchaseName { get; set; }
        public decimal? DebtLimit { get; set; }
        public decimal? RemainingDebt { get; set; }
        public string CustomerGroup { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public bool? IsAuto { get; set; }
        public bool? AccountLogin { get; set; }
        public Guid? AccountId { get; set; }
        public string AccountEmail { get; set; }
        public bool? AccountEmailVerified { get; set; }
        public string AccountUsername { get; set; }
        public DateTime? AccountCreatedDate { get; set; }
        public string AccountPhone { get; set; }
        public bool? AccountPhoneVerified { get; set; }
        public string Tenant { get; set; }
        public bool? BidActive { get; set; }
        public int? BidQuantity { get; set; }
        public bool? TranActive { get; set; }
        public string IdName { get; set; }
        public string IdNumber { get; set; }
        public DateTime? IdDate { get; set; }
        public string IdIssuer { get; set; }
        public string IdImage1 { get; set; }
        public string IdImage2 { get; set; }
        public int? IdStatus { get; set; }
        public int? Level { get; set; }
        public string Representative { get; set; }
        public decimal? Revenue { get; set; }
        public decimal? RevenueMonth { get; set; }
        public string? CccdNumber { get; set; }
        public DateTime? DateRange { get; set; } 
        public DateTime? Birthday { get; set; }
        public string IssuedBy { get; set; }
        public int? BmapGroup { get; set; }
        public  CustomerSource CustomerSource { get; set; }
        public  GroupEmployee GroupEmployee { get; set; }
        public  PriceListPurchase PriceListPurchase { get; set; }
        public  ICollection<CouponCustomer> CouponCustomer { get; set; }
        public  ICollection<CustomerAddress> CustomerAddress { get; set; }
        public  ICollection<CustomerBank> CustomerBank { get; set; }
        public  ICollection<CustomerBusinessMapping> CustomerBusinessMapping { get; set; }
        public  ICollection<CustomerContact> CustomerContact { get; set; }
        public  ICollection<CustomerGroupMapping> CustomerGroupMapping { get; set; }
        public  ICollection<CustomerPriceListCross> CustomerPriceListCross { get; set; }
        public  ICollection<CustomerProfile> CustomerProfile { get; set; }
        public  ICollection<Order> Order { get; set; }
        public  ICollection<PromotionCustomer> PromotionCustomer { get; set; }
        public  ICollection<ReturnOrder> ReturnOrder { get; set; }
        public virtual ICollection<SalesDiscount> SalesDiscount { get; set; }
    }
}
