// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class CustomerContact : Entity, IAggregateRoot
    {
        public Guid? CustomerId { get; set; }
        public Guid? EmployeeId { get; set; }
        public string Name { get; set; }
        public int? Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string JobTitle { get; set; }
        public string Tags { get; set; }
        public string Address { get; set; }
        public int? Status { get; set; }
        public int? SortOrder { get; set; }
        public string? Note { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}