// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class CustomerPriceListCross : Entity, IAggregateRoot
    {
        public Guid CustomerId { get; set; }
        public Guid PriceListCrossId { get; set; }
        public string PriceListCrossName { get; set; }
        public Guid RouterShippingId { get; set; }
        public string RouterShipping { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }

        public  Customer Customer { get; set; }
        public  PriceListCross PriceListCross { get; set; }
    }
}