// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class CustomerBusinessMapping : Entity, IAggregateRoot
    {
        public Guid CustomerId { get; set; }
        public Guid BusinessId { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedByName { get; set; }

        public  Business Business { get; set; }
        public  Customer Customer { get; set; }
    }
}