// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class District : Entity, IAggregateRoot
    {
        public string? Code { get; set; }
        public string? Name { get; set; }
        public Guid? StateProvinceId { get; set; }
       
    }
}
