// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Employee : Entity, IAggregateRoot
    {
        public Employee()
        {
            GroupEmployeeMapping = new HashSet<GroupEmployeeMapping>();
            CustomerAddresses = new HashSet<CustomerAddress>();
            CustomerBanks = new HashSet<CustomerBank>();
            CustomerContacts = new HashSet<CustomerContact>();
        }

        public bool? IsCustomer { get; set; }
        public Guid AccountId { get; set; }
        public string? AccountName { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string Address { get; set; }
        public string TaxCode { get; set; }
        public int? Gender { get; set; }
        public int? Year { get; set; }
        public int? Month { get; set; }
        public int? Day { get; set; }
        public string GroupEmployee { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public ICollection<GroupEmployeeMapping> GroupEmployeeMapping { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<CustomerBank> CustomerBanks { get; set; }
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
    }
}