// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class ExchangeRate : Entity, IAggregateRoot
    {
        public Guid? CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public decimal? Rate { get; set; }
        public DateTime? ActiveDate { get; set; }
        public int? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }

        public  Currency Currency { get; set; }
    }
}