// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class ExportWarehouseProduct : Entity, IAggregateRoot
    {
        public Guid Id { get; set; }

        public Guid? OrderId { get; set; }

        public string OrderCode { get; set; }

        public Guid? OrderProductId { get; set; }

        public Guid? ExportWarehouseId { get; set; }

        public Guid? ProductId { get; set; }

        public string ProductCode { get; set; }

        public string ProductName { get; set; }

        public string ProductImage { get; set; }

        public string WarehouseCode { get; set; }

        public string WarehouseName { get; set; }

        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitCode { get; set; }

        public string UnitName { get; set; }

        public double QuantityRequest { get; set; }
        public double QuantityExported { get; set; }

        public string Note { get; set; }

        /// <summary>
        /// Thứ tự
        /// </summary>
        public int? DisplayOrder { get; set; }

        public virtual ICollection<ExportProduct> ExportProducts { get; set; } = new List<ExportProduct>();

        public virtual ExportWarehouse ExportWarehouse { get; set; }

        public virtual OrderProduct OrderProduct { get; set; }
    }
}