// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;
using VFi.Domain.SO.Enums;

namespace VFi.Domain.SO.Models
{
    public partial class ExportWarehouse : Entity, IAggregateRoot
    {
        public ExportWarehouse()
        {
            ExportWarehouseProduct = new HashSet<ExportWarehouseProduct>();
        }
         
        public string Code { get; set; }
        public Guid? OrderId { get; set; }
        public string OrderCode { get; set; }
        public Guid? CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// Kho
        /// </summary>
        public Guid? WarehouseId { get; set; }
        /// <summary>
        /// Kho
        /// </summary>
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public int? DeliveryStatus { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryCountry { get; set; }
        public string DeliveryProvince { get; set; }
        public string DeliveryDistrict { get; set; }
        public string DeliveryWard { get; set; }
        public string DeliveryNote { get; set; }
        public DateTime? EstimatedDeliveryDate { get; set; }
        public Guid? DeliveryMethodId { get; set; }
        public string DeliveryMethodCode { get; set; }
        public string DeliveryMethodName { get; set; }
        public Guid? ShippingMethodId { get; set; }
        public string ShippingMethodCode { get; set; }
        public string ShippingMethodName { get; set; }
        public int? Status { get; set; }
        public int? StatusExport { get; set; }
        public string Note { get; set; }
        public Guid? RequestBy { get; set; }
        public string RequestByName { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? ApproveDate { get; set; }
        public Guid? ApproveBy { get; set; }
        public string ApproveByName { get; set; }
        public string ApproveComment { get; set; }
        public string FulfillmentRequestCode { get; set; }
        public string File { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  Order Order { get; set; }
        public  ICollection<ExportWarehouseProduct> ExportWarehouseProduct { get; set; }
        public virtual ICollection<Export> Exports { get; set; } = new List<Export>();
    }
}
