// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Export : Entity, IAggregateRoot
    {
        public Guid Id { get; set; }

        public Guid? ExportWarehouseId { get; set; }

        /// <summary>
        /// Số phiếu
        /// </summary>
        public string Code { get; set; }

        /// <summary>
        /// Ngày xuất kho
        /// </summary>
        public DateTime? ExportDate { get; set; }

        /// <summary>
        /// Người phụ trách
        /// </summary>
        public Guid? EmployeeId { get; set; }

        public string EmployeeCode { get; set; }

        public string EmployeeName { get; set; }

        /// <summary>
        /// Trạng thái :1#Chờ xử lý;2#Đã xuất khẩu
        /// </summary>
        public int? Status { get; set; }

        public double? TotalQuantity { get; set; }

        public string Note { get; set; }

        public string File { get; set; }

        public Guid? ApproveBy { get; set; }

        public DateTime? ApproveDate { get; set; }

        public string ApproveByName { get; set; }

        public string ApproveComment { get; set; }

        public Guid? CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public Guid? UpdatedBy { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string CreatedByName { get; set; }

        public string UpdatedByName { get; set; }

        public virtual ICollection<ExportProduct> ExportProducts { get; set; } = new List<ExportProduct>();
        public virtual ExportWarehouse ExportWarehouse { get; set; }
    }
}