// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class ExportProduct : Entity, IAggregateRoot
    {
        public Guid Id { get; set; }

        public Guid? ExportId { get; set; }

        public Guid? ExportWarehouseProductId { get; set; }

        public Guid? ProductId { get; set; }

        public string ProductCode { get; set; }

        public string ProductName { get; set; }

        public string ProductImage { get; set; }

        public string Origin { get; set; }

        public string UnitType { get; set; }

        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitCode { get; set; }

        public string UnitName { get; set; }

        public double? Quantity { get; set; }

        public string Note { get; set; }

        public int? DisplayOrder { get; set; }

        public Guid? CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public Guid? UpdatedBy { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string CreatedByName { get; set; }

        public string UpdatedByName { get; set; }

        public virtual Export Export { get; set; }

        public virtual ExportWarehouseProduct ExportWarehouseProduct { get; set; }
    }
}