// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class GroupEmployee : Entity, IAggregateRoot
    {
        public GroupEmployee()
        {
            Contract = new HashSet<Contract>();
            Customer = new HashSet<Customer>();
            GroupEmployeeMapping = new HashSet<GroupEmployeeMapping>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  ICollection<Contract> Contract { get; set; }
        public  ICollection<Customer> Customer { get; set; }
        public  ICollection<GroupEmployeeMapping> GroupEmployeeMapping { get; set; }
    }
}