// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class GroupEmployeeMapping : Entity, IAggregateRoot
    {
        public Guid? EmployeeId { get; set; }
        public Guid? GroupEmployeeId { get; set; }
        public bool? IsLeader { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedByName { get; set; }

        public  Employee Employee { get; set; }
        public  GroupEmployee GroupEmployee { get; set; }
    }
}