// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class LeadCampaign : Entity, IAggregateRoot
    {
        public Guid Id { get; set; }

        public Guid? LeadId { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public string Name { get; set; }

        public Guid? CampaignId { get; set; }

        public string Campaign { get; set; }

        /// <summary>
        /// Bước chăm sóc
        /// </summary>
        public Guid? StateId { get; set; }

        public string State { get; set; }

        public DateTime? StateDate { get; set; }

        public Guid? Leader { get; set; }

        public string LeaderName { get; set; }

        public string Member { get; set; }

        public int? Status { get; set; }

        public Guid? CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public Guid? UpdatedBy { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string CreatedByName { get; set; }

        public string UpdatedByName { get; set; }

        public virtual Campaign CampaignNavigation { get; set; }

        public virtual Lead Lead { get; set; }
    }
}
