// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class LeadActivity : Entity, IAggregateRoot
    {
        public Guid Id { get; set; }

        public Guid? LeadId { get; set; }

        public Guid? CampaignId { get; set; }

        public string Campaign { get; set; }

        public string Type { get; set; }

        public string Name { get; set; }

        public string Body { get; set; }

        public DateTime? ActualDate { get; set; }

        public string Attachment { get; set; }

        public int? Status { get; set; }

        public Guid? CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public Guid? UpdatedBy { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string CreatedByName { get; set; }

        public string UpdatedByName { get; set; }
        public virtual Lead Lead { get; set; }
    }
}