// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class LeadTopicSuggest : Entity, IAggregateRoot
    {
        public Guid Id { get; set; }

        public Guid LeadId { get; set; }

        public string Name { get; set; }

        public string Page { get; set; }

        public string Topic { get; set; }

        public string Keyword { get; set; }

        public int? Priority { get; set; }

        public int? Point { get; set; }

        public Guid? CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public Guid? UpdatedBy { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string CreatedByName { get; set; }

        public string UpdatedByName { get; set; }

        public virtual Lead Lead { get; set; }
    }
}
