// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class MESProductionOrder
    {
        public string Id { get; set; } = null!;
        public string Code { get; set; } = null!;
        public string? Note { get; set; }
        public int? Status { get; set; }
        public DateTime? RequestDate { get; set; }
        public Guid? CustomerId { get; set; }
        public string? CustomerCode { get; set; }
        public string? CustomerName { get; set; }
        public string? Email { get; set; }
        public string? Phone { get; set; }
        public string? Address { get; set; }
        public Guid? EmployeeId { get; set; }
        public string? EmployeeCode { get; set; }
        public string? EmployeeName { get; set; }
        public DateTime? DateNeed { get; set; }
        public Guid? OrderId { get; set; }
        public string? OrderNumber { get; set; }
        public Guid? SaleEmployeeId { get; set; }
        public string? SaleEmployeeCode { get; set; }
        public string? SaleEmployeeName { get; set; }
        public int? Type { get; set; }
        public DateTime? EstimateDate { get; set; }
        public string? File { get; set; }
        public List<MESProductionOrdersDetail> ProductionOrdersDetail { get; set; }
    }
    public partial class MESProductionOrdersDetail
    {
        public Guid? OrderProductId { get; set; }
        public Guid? ProductId { get; set; }
        public string? ProductCode { get; set; }
        public string? ProductName { get; set; }
        public string? ProductImage { get; set; }
        public string? Sku { get; set; }
        public string? Gtin { get; set; }
        public string? Origin { get; set; }
        public string? UnitType { get; set; }
        public string? UnitCode { get; set; }
        public string? UnitName { get; set; }
        public double? Quantity { get; set; }
        public string? Note { get; set; }
        public double? EstimatedDeliveryQuantity { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public bool? IsWorkOrdered { get; set; }
        public string? ProductionOrdersCode { get; set; }
        public bool? IsEstimated { get; set; }
        public bool? IsBom { get; set; }
        public int? EstimateStatus { get; set; }
    }
}
