// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class OrderTracking : Entity, IAggregateRoot
    {
        public Guid? OrderId { get; set; }
        public Guid? OrderExpressId { get; set; }
        public string Name { get; set; }
        public int? Status { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public DateTime? TrackingDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  Order Order { get; set; }
        public  OrderExpress OrderExpress { get; set; }
    }
}