// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class OrderCost : Entity, IAggregateRoot
    {
        public Guid? QuotationId { get; set; }
        public Guid? OrderId { get; set; }
        public Guid? ExpenseId { get; set; }
        public int? Type { get; set; }
        public double? Rate { get; set; }
        public decimal? Amount { get; set; }
        public int? Status { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public  Expense Expense { get; set; }
        public  Order Order { get; set; }
    }
}