// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class OrderServiceAdd : Entity, IAggregateRoot
    {
        public Guid? OrderId { get; set; }
        public Guid? QuotationId { get; set; }
        public Guid? ServiceAddId { get; set; }
        public string ServiceAddName { get; set; }
        public decimal? Price { get; set; }
        public string Currency { get; set; }
        public string Calculation { get; set; }
        public int? Status { get; set; }
        public string Note { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }
        public decimal? ExchangeRate { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? OrderExpressId { get; set; }

        public  Order Order { get; set; }
        public  OrderExpress OrderExpress { get; set; }
        public  Quotation Quotation { get; set; }
        public  ServiceAdd ServiceAdd { get; set; }
    }
}