// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class OrderProduct : Entity, IAggregateRoot
    {
        public OrderProduct()
        {
            ExportWarehouseProduct = new HashSet<ExportWarehouseProduct>();
            RequestPurchaseProduct = new HashSet<RequestPurchaseProduct>();
            ReturnOrderProduct = new HashSet<ReturnOrderProduct>();
            DeliveryProduct = new HashSet<DeliveryProduct>();
        }

        public Guid? OrderId { get; set; }
        public string OrderCode { get; set; }
        public Guid? ContractId { get; set; }
        public string ContractName { get; set; }
        public Guid? QuotationId { get; set; }
        public string QuotationName { get; set; }
        public Guid ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string Origin { get; set; }
        public Guid? WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public Guid? PriceListId { get; set; }
        public string PriceListName { get; set; }
        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitType { get; set; }
        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public decimal? Quantity { get; set; }
        /// <summary>
        /// Đơn giá
        /// </summary>
        public decimal? UnitPrice { get; set; }
        /// <summary>
        /// Tiền chiết khấu phân bổ
        /// </summary>
        public decimal? DiscountAmountDistribution { get; set; }
        /// <summary>
        /// Loại chiết khấu: 0-Phần trăm, 1-Giá trị
        /// </summary>
        public int? DiscountType { get; set; }
        /// <summary>
        /// % Chiết khấu
        /// </summary>
        public double? DiscountPercent { get; set; }
        /// <summary>
        /// Chiết khấu
        /// </summary>
        public decimal? AmountDiscount { get; set; }
        /// <summary>
        /// % Chiết khấu
        /// </summary>
        public double? DiscountTotal { get; set; }
        public double? TaxRate { get; set; }
        public string Tax { get; set; }
        public string TaxCode { get; set; }
        /// <summary>
        /// Ngày nhận hàng dự kiến
        /// </summary>
        public DateTime? ExpectedDate { get; set; }
        public string Note { get; set; }
        public string Attributes { get; set; }
        public decimal? QuantitySales { get; set; }
        public decimal? QuantitySaleActual { get; set; }
        public decimal? QuantityReturned { get; set; }
        public decimal? QuantityReturnedActual { get; set; }
        /// <summary>
        /// Số lượng đã xuất
        /// </summary>
        public decimal? QuantityExported { get; set; }
        /// <summary>
        /// Số lượng đã đề nghị mua
        /// </summary>
        public decimal? QuantityPurchased { get; set; }

        public double? QuantityProductioned { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public int? DeliveryStatus { get; set; }
        public int? DeliveryQuantity { get; set; }
        public string CommodityGroup { get; set; }
        public string SurchargeGroup { get; set; }
        public decimal? Surcharge { get; set; }

        public string BidUsername { get; set; }
        public string SellerId { get; set; }

        public string SourceLink { get; set; }
        public string SourceCode { get; set; }
        public decimal? DiscountAmount { get; set; }
        public DateTime? EstimatedDeliveryDate { get; set; }
        public decimal? ReturnAmount { get; set; }
        public decimal? SaleAmount { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode1 { get; set; }
        /// <summary>
        /// Mã quy cách 2
        /// </summary>
        public string SpecificationCode2 { get; set; }
        /// <summary>
        /// Mã quy cách 3
        /// </summary>
        public string SpecificationCode3 { get; set; }
        /// <summary>
        /// Mã quy cách 4
        /// </summary>
        public string SpecificationCode4 { get; set; }
        /// <summary>
        /// Mã quy cách 5
        /// </summary>
        public string SpecificationCode5 { get; set; }
        /// <summary>
        /// Mã quy cách 6
        /// </summary>
        public string SpecificationCode6 { get; set; }
        /// <summary>
        /// Mã quy cách 7
        /// </summary>
        public string SpecificationCode7 { get; set; }
        /// <summary>
        /// Mã quy cách 8
        /// </summary>
        public string SpecificationCode8 { get; set; }
        /// <summary>
        /// Mã quy cách 9
        /// </summary>
        public string SpecificationCode9 { get; set; }
        /// <summary>
        /// Mã quy cách 10
        /// </summary>
        public string SpecificationCode10 { get; set; }
        public string SpecificationCodeJson { get; set; }
        public  Contract Contract { get; set; }
        public  Order Order { get; set; }
        public  Quotation Quotation { get; set; }
        public virtual ICollection<DeliveryProduct> DeliveryProduct { get; set; }
        public  ICollection<ExportWarehouseProduct> ExportWarehouseProduct { get; set; }
        public  ICollection<RequestPurchaseProduct> RequestPurchaseProduct { get; set; }
        public  ICollection<ReturnOrderProduct> ReturnOrderProduct { get; set; }
    }
}
