// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Order : Entity, IAggregateRoot
    {
        public Order()
        {
            ExportWarehouse = new HashSet<ExportWarehouse>();
            OrderCost = new HashSet<OrderCost>();
            OrderInvoice = new HashSet<OrderInvoice>();
            OrderProduct = new HashSet<OrderProduct>();
            OrderServiceAdd = new HashSet<OrderServiceAdd>();
            OrderTracking = new HashSet<OrderTracking>();
            PaymentInvoice = new HashSet<PaymentInvoice>();
        } 
        public string OrderType { get; set; }
        public string Code { get; set; }
        public DateTime? OrderDate { get; set; }
        public Guid? CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Guid? StoreId { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public Guid? ContractId { get; set; }
        public string ContractName { get; set; }
        public Guid? QuotationId { get; set; }
        public string QuotationName { get; set; }
        public Guid? ChannelId { get; set; }
        public string ChannelName { get; set; }
        public int? Status { get; set; }
        public string Currency { get; set; }
        public string CurrencyName { get; set; }
        public Guid? PriceListId { get; set; }
        public string PriceListName { get; set; }
        public Guid? PaymentTermId { get; set; }
        public string PaymentTermName { get; set; }
        public string PaymentMethodName { get; set; }
        /// <summary>
        /// Điều khoản thanh toán
        /// </summary>
        public Guid? PaymentMethodId { get; set; }
        public int? PaymentStatus { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryPhone { get; set; }
        public string DeliveryZipCode { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryCountry { get; set; }
        public string DeliveryProvince { get; set; }
        public string DeliveryDistrict { get; set; }
        public string DeliveryWard { get; set; }
        public string DeliveryNote { get; set; }
        public DateTime? EstimatedDeliveryDate { get; set; }
        public Guid? DeliveryMethodId { get; set; }
        public string DeliveryMethodCode { get; set; }
        public string DeliveryMethodName { get; set; }
        public int? DeliveryStatus { get; set; }
        public string DeliveryTracking { get; set; }
        public string DeliveryCarrier { get; set; }
        public int? DeliveryPackage { get; set; }
        public bool? IsBill { get; set; }
        public string BillName { get; set; }
        public string BillAddress { get; set; }
        public string BillCountry { get; set; }
        public string BillProvince { get; set; }
        public string BillDistrict { get; set; }
        public string BillWard { get; set; }
        public int? BillStatus { get; set; }
        public Guid? ShippingMethodId { get; set; }
        public string ShippingMethodCode { get; set; }
        public string ShippingMethodName { get; set; }
        public int? TypeDiscount { get; set; }
        public double? DiscountRate { get; set; }
        public int? TypeCriteria { get; set; }
        public decimal? AmountDiscount { get; set; }
        public string Note { get; set; }
        public string InternalNote { get; set; }
        public Guid? GroupEmployeeId { get; set; }
        public string GroupEmployeeName { get; set; }
        public Guid? AccountId { get; set; }
        public string AccountName { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public string PurchaseGroup { get; set; }
        public int? BuyFee { get; set; }
        public int? DomesticStatus { get; set; }
        public string RouterShipping { get; set; }
        public string DomesticTracking { get; set; }
        public DateTime? DomesticDeliveryDate { get; set; }
        public string DomesticCarrier { get; set; }
        public int? DomesticPackage { get; set; }
        public string CommodityGroup { get; set; }
        public decimal? AirFreight { get; set; }
        public decimal? SeaFreight { get; set; }
        public decimal? Surcharge { get; set; }
        public DateTime? ApproveDate { get; set; }
        public Guid? ApproveBy { get; set; }
        public string ApproveByName { get; set; }
        public string ApproveComment { get; set; }
        public decimal? ExchangeRate { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public decimal? Total { get; set; }
        public decimal? Paid { get; set; }
        public int? TypeDocument { get; set; }
        public decimal? DomesticShiping { get; set; }
        public int? Weight { get; set; }
        public int? Width { get; set; }
        public int? Height { get; set; }
        public int? Length { get; set; }
        public decimal? TotalAmountTax { get; set; }
        public string File { get; set; }
        public string Calculation { get; set; }
        public string? ShipmentRouting { get; set; }
        public DateTime? PaymentExpiryDate { get; set; }

        public virtual SalesChannel Channel { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual Quotation Quotation { get; set; }
        public virtual ShippingMethod ShippingMethod { get; set; }
        public virtual ICollection<ExportWarehouse> ExportWarehouse { get; set; }
        public virtual ICollection<OrderCost> OrderCost { get; set; }
        public virtual ICollection<OrderInvoice> OrderInvoice { get; set; }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ICollection<OrderServiceAdd> OrderServiceAdd { get; set; }
        public virtual ICollection<OrderTracking> OrderTracking { get; set; }
        public virtual ICollection<PaymentInvoice> PaymentInvoice { get; set; }
    }
}
