// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class PaymentInvoice : Entity, IAggregateRoot
    {
        public string Type { get; set; }
        public string Code { get; set; }
        public Guid? OrderId { get; set; }
        public string OrderCode { get; set; }
        public Guid? SaleDiscountId { get; set; }
        public Guid? ReturnOrderId { get; set; }
        public string Description { get; set; }
        public decimal? Amount { get; set; }
        public string Currency { get; set; }
        public string CurrencyName { get; set; }
        public string Calculation { get; set; }
        public decimal? ExchangeRate { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentMethodCode { get; set; }
        /// <summary>
        /// Điều khoản thanh toán
        /// </summary>
        public Guid? PaymentMethodId { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string BankNumber { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentNote { get; set; }
        public string Note { get; set; }
        public int? Status { get; set; }
        public int? Locked { get; set; }
        public int? PaymentStatus { get; set; }
        public Guid? AccountId { get; set; }
        public string AccountName { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public Guid? CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string OrderExpressCode { get; set; }
        public Guid? OrderExpressId { get; set; }
        public string File { get; set; }

        public  Order Order { get; set; }
        public  OrderExpress OrderExpress { get; set; }
        public  PaymentMethod PaymentMethod { get; set; }
        public  ReturnOrder ReturnOrder { get; set; }
        public  SalesDiscount SaleDiscount { get; set; }
    }
}