// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class PriceList : Entity, IAggregateRoot
    {
        public PriceList()
        {
            PriceListDetail = new HashSet<PriceListDetail>();
            StorePriceList = new HashSet<StorePriceList>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Currency { get; set; }
        public string CurrencyName { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  ICollection<PriceListDetail> PriceListDetail { get; set; }
        public  ICollection<StorePriceList> StorePriceList { get; set; }
    }
}