// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class PriceListCross : Entity, IAggregateRoot
    {
        public PriceListCross()
        {
            CustomerPriceListCross = new HashSet<CustomerPriceListCross>();
            PriceListCrossDetail = new HashSet<PriceListCrossDetail>();
        }
         
        public Guid? RouterShippingId { get; set; }
        public string RouterShipping { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public bool? Default { get; set; }

        public  RouteShipping RouterShippingNavigation { get; set; }
        public  ICollection<CustomerPriceListCross> CustomerPriceListCross { get; set; }
        public  ICollection<PriceListCrossDetail> PriceListCrossDetail { get; set; }
    }
}