// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class PriceListDetail : Entity, IAggregateRoot
    {
        public Guid PriceListId { get; set; }
        public Guid? ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitType { get; set; }
        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public int? QuantityMin { get; set; }
        public int? Type { get; set; }
        public decimal? FixPrice { get; set; }
        public int? TypeDiscount { get; set; }
        public double? DiscountRate { get; set; }
        public decimal? DiscountValue { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  PriceList PriceList { get; set; }
    }
}