// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class PriceListPurchaseDetail : Entity, IAggregateRoot
    {
        public Guid PriceListPurchaseId { get; set; }
        public string PriceListPurchase { get; set; }
        public string Note { get; set; }
        public Guid? PurchaseGroupId { get; set; }
        public string PurchaseGroupCode { get; set; }
        public string PurchaseGroupName { get; set; }
        public int? BuyFee { get; set; }
        public decimal? BuyFeeMin { get; set; }
        public decimal? BuyFeeFix { get; set; }
        public int? Status { get; set; }
        public string Currency { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public int? DisplayOrder { get; set; }

        public  PriceListPurchase PriceListPurchaseNavigation { get; set; }
        public  PurchaseGroup PurchaseGroup { get; set; }
    }
}