// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models;

public partial class ProductionOrder : Entity, IAggregateRoot
{
    public string Code { get; set; }
    public string ProductionOrderCode { get; set; }

    public string Note { get; set; }

    /// <summary>
    /// 1. chờ xử lý, 2 xác nhận, 3 hoàn thành
    /// </summary>
    public int? Status { get; set; }

    public DateTime? RequestDate { get; set; }

    public Guid? CustomerId { get; set; }

    public string CustomerCode { get; set; }

    public string CustomerName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public Guid? EmployeeId { get; set; }

    public string EmployeeCode { get; set; }

    public string EmployeeName { get; set; }

    public DateTime? DateNeed { get; set; }
    public Guid? OrderId { get; set; }

    public string OrderNumber { get; set; }

    public Guid? SaleEmployeeId { get; set; }

    public string SaleEmployeeCode { get; set; }

    public string SaleEmployeeName { get; set; }

    /// <summary>
    /// Loại phiếu/ 1: Yêu cầu dự toán, 2: Yêu cầu sản xuất
    /// </summary>
    public int? Type { get; set; }

    /// <summary>
    /// Hạn dự toán
    /// </summary>
    public DateTime? EstimateDate { get; set; }
    public string File { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedByName { get; set; }

    public string UpdatedByName { get; set; }

    public  ICollection<ProductionOrdersDetail> ProductionOrdersDetail { get; set; } = new List<ProductionOrdersDetail>();
}