// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class ProductionOrdersDetail : Entity, IAggregateRoot
    {
        public Guid ProductionOrdersId { get; set; }
        public Guid? OrderId { get; set; }
        public string? OrderCode { get; set; }
        public Guid? OrderProductId { get; set; }
        public Guid? ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string Sku { get; set; }
        public string Gtin { get; set; }
        public string Origin { get; set; }
        public string UnitType { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public double? Quantity { get; set; }
        public string Note { get; set; }
        public double? EstimatedDeliveryQuantity { get; set; }
        public DateTime? DeliveryDate { get; set; }
        /// <summary>
        /// Trạng thái đã lập lệnh sản xuất
        /// </summary>
        public bool? IsWorkOrdered { get; set; }
        public string ProductionOrdersCode { get; set; }
        /// <summary>
        /// Trạng thái đã dự toán
        /// </summary>
        public bool? IsEstimated { get; set; }
        public bool? IsBom { get; set; }
        /// <summary>
        /// Chờ lập lệnh sx:1, Đang sx: 2, Hoàn thành: 3, Hủy sx: 4
        /// </summary>
        public int? Status { get; set; }
        public DateTime? EstimatedDate { get; set; }
        /// <summary>
        /// Trạng thái dự toán. 1: Chưa dự toán. 2. Đang dự toán. 3. Đã dự toán
        /// </summary>
        public int? EstimateStatus { get; set; }
        /// <summary>
        /// Phuong phap
        /// </summary>
        public string Solution { get; set; }
        /// <summary>
        /// Van chuyen
        /// </summary>
        public string Transport { get; set; }
        /// <summary>
        /// Cao
        /// </summary>
        public double? Height { get; set; }
        /// <summary>
        /// So luong/kien
        /// </summary>
        public double? Package { get; set; }
        /// <summary>
        /// the tich
        /// </summary>
        public double? Volume { get; set; }
        /// <summary>
        /// Chieu dai
        /// </summary>
        public double? Length { get; set; }
        /// <summary>
        /// Can nang
        /// </summary>
        public double? Weight { get; set; }
        /// <summary>
        /// Chieu rong
        /// </summary>
        public double? Width { get; set; }
        public string CancelReason { get; set; }
        public int? DisplayOrder { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public  ProductionOrder ProductionOrder { get; set; }
    }
}