// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Product : Entity, IAggregateRoot
    {
        public string? Code { get; set; }
        public string? Name { get; set; }
        public string? UnitType { get; set; }
        public string? UnitName { get; set; }
        public string? Price { get; set; }
        public string? UnitCode { get; set; }
        public string? Currency { get; set; }
        public string? StockQuantity { get; set; }
    }
}
