// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class PromotionByValue : Entity, IAggregateRoot
    {
        public PromotionByValue()
        {
            PromotionProduct = new HashSet<PromotionProduct>();
            PromotionProductBuy = new HashSet<PromotionProductBuy>();
        }
         
        public Guid? PromotionId { get; set; }
        public Guid? ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int? Type { get; set; }
        public decimal? MinOrderPrice { get; set; }
        public decimal? LimitTotalValue { get; set; }
        public double? DiscountPercent { get; set; }
        public decimal? ReduceAmount { get; set; }
        public decimal? FixPrice { get; set; }
        public int? TypeBonus { get; set; }
        public int? TypeBuy { get; set; }
        public double? Quantity { get; set; }
        public double? QuantityBuy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }

        public  Promotion Promotion { get; set; }
        public  ICollection<PromotionProduct> PromotionProduct { get; set; }
        public  ICollection<PromotionProductBuy> PromotionProductBuy { get; set; }
    }
}