// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class PromotionCustomerGroup : Entity, IAggregateRoot
    {
        public Guid? PromotionId { get; set; }
        public Guid? CustomerGroupId { get; set; }

        public  CustomerGroup CustomerGroup { get; set; }
        public  Promotion Promotion { get; set; }
    }
}