// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class QuotationAttachment : Entity, IAggregateRoot
    {
        public Guid QuotationId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string AttachType { get; set; }
        public int? DisplayOrder { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }

        public  Quotation Quotation { get; set; }
    }
}