// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Report : Entity, IAggregateRoot
    {
        public Report()
        {
            RptSoChiTietBanHang = new HashSet<RptSoChiTietBanHang>();
            RptTinhHinhThucHienDonBanHang = new HashSet<RptTinhHinhThucHienDonBanHang>();
            RptTinhHinhThucHienHopDongBan = new HashSet<RptTinhHinhThucHienHopDongBan>();
            RptTongHopBanHangTheoKhachHang = new HashSet<RptTongHopBanHangTheoKhachHang>();
            RptTongHopBanHangTheoMatHang = new HashSet<RptTongHopBanHangTheoMatHang>();
            RptTongHopBanHangTheoNhanVien = new HashSet<RptTongHopBanHangTheoNhanVien>();
            RptTongHopBanHangTheoNhomKhachHang = new HashSet<RptTongHopBanHangTheoNhomKhachHang>();
            RptTongHopBanHangTheoKhachHangVaDonBanHang = new HashSet<RptTongHopBanHangTheoKhachHangVaDonBanHang>();
            RptTongHopBanHangTheoMatHangVaKhachHang = new HashSet<RptTongHopBanHangTheoMatHangVaKhachHang>();
        }
         
        public string Name { get; set; }
        public Guid? ReportTypeId { get; set; }
        public string ReportTypeCode { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public string CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string CategoryRootId { get; set; }
        public string CategoryRootName { get; set; }
        public string ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string CustomerGroupId { get; set; }
        public string CustomerGroupCode { get; set; }
        public string CustomerGroupName { get; set; }
        public string CurrencyCode { get; set; }
        public int? Status { get; set; }
        public DateTime? LoadDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedByName { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedByName { get; set; }

        public virtual ReportType ReportType { get; set; }
        public virtual ICollection<RptSoChiTietBanHang> RptSoChiTietBanHang { get; set; }
        public virtual ICollection<RptTinhHinhThucHienDonBanHang> RptTinhHinhThucHienDonBanHang { get; set; }
        public virtual ICollection<RptTinhHinhThucHienHopDongBan> RptTinhHinhThucHienHopDongBan { get; set; }
        public virtual ICollection<RptTongHopBanHangTheoKhachHang> RptTongHopBanHangTheoKhachHang { get; set; }
        public virtual ICollection<RptTongHopBanHangTheoMatHang> RptTongHopBanHangTheoMatHang { get; set; }
        public virtual ICollection<RptTongHopBanHangTheoNhanVien> RptTongHopBanHangTheoNhanVien { get; set; }
        public virtual ICollection<RptTongHopBanHangTheoNhomKhachHang> RptTongHopBanHangTheoNhomKhachHang { get; set; }
        public virtual ICollection<RptTongHopBanHangTheoKhachHangVaDonBanHang> RptTongHopBanHangTheoKhachHangVaDonBanHang { get; set; }
        public virtual ICollection<RptTongHopBanHangTheoMatHangVaKhachHang> RptTongHopBanHangTheoMatHangVaKhachHang { get; set; }
    }
}