// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class RequestPurchase : Entity, IAggregateRoot
    {
        public RequestPurchase()
        {
            RequestPurchaseProduct = new HashSet<RequestPurchaseProduct>();
        }
 
        /// <summary>
        /// Số đề nghị
        /// </summary>
        public string Code { get; set; }
        public Guid? RequestBy { get; set; }
        public string RequestByName { get; set; }
        public string RequestByEmail { get; set; }
        public DateTime? RequestDate { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public string Calculation { get; set; }
        /// <summary>
        /// Tỷ giá
        /// </summary>
        public decimal? ExchangeRate { get; set; }
        /// <summary>
        /// Mục đích đề nghị
        /// </summary>
        public string Proposal { get; set; }
        public string Note { get; set; }
        public DateTime? ApproveDate { get; set; }
        public Guid? ApproveBy { get; set; }
        public string ApproveByName { get; set; }
        public string ApproveComment { get; set; }
        /// <summary>
        /// Trạng thái: 1-Sử dụng, 0-Không sử dụng
        /// </summary>
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        /// <summary>
        /// Số lượng đề nghị
        /// </summary>
        public double? QuantityRequest { get; set; }
        /// <summary>
        /// Số lượng duyệt
        /// </summary>
        public double? QuantityApproved { get; set; }
        public int? StatusPurchase { get; set; }
        /// <summary>
        /// Số đề nghị PO
        /// </summary>
        public string PurchaseRequestCode { get; set; }
        public Guid? OrderId { get; set; }
        /// <summary>
        /// Số đề nghị PO
        /// </summary>
        public string OrderCode { get; set; }
        public DateTime? Podate { get; set; }
        public int? Postatus { get; set; }
        public string File { get; set; }
        public double? QuantityPurchase { get; set; }
        public double? QuantityPurchased { get; set; }

        public  ICollection<RequestPurchaseProduct> RequestPurchaseProduct { get; set; }
    }
}