// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class RequestQuote : Entity, IAggregateRoot
    {
        public RequestQuote()
        {
            Quotation = new HashSet<Quotation>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? DueDate { get; set; }
        public Guid? StoreId { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public Guid? CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Guid? EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Note { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public Guid? ChannelId { get; set; }
        public string ChannelCode { get; set; }
        public string ChannelName { get; set; }

        public  SalesChannel Channel { get; set; }
        public  Store Store { get; set; }
        public  ICollection<Quotation> Quotation { get; set; }
    }
}