// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;
using VFi.Domain.SO.Enums;

namespace VFi.Domain.SO.Models
{
    public partial class RequestPurchaseProduct : Entity, IAggregateRoot
    {
        public Guid RequestPurchaseId { get; set; }
        public Guid? OrderId { get; set; }
        public string OrderCode { get; set; }
        public Guid? OrderProductId { get; set; }
        public Guid? ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string SourceLink { get; set; }
        public decimal? ShippingFee { get; set; }
        public string Origin { get; set; }
        public string UnitType { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public decimal? UnitPrice { get; set; }
        public string Currency { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public int? PriorityLevel { get; set; }
        /// <summary>
        /// Mã nhà cung cấp
        /// </summary>
        public string VendorCode { get; set; }
        /// <summary>
        /// Tên nhà cung cấp
        /// </summary>
        public string VendorName { get; set; }
        public int? Status { get; set; }
        public double? QuantityRequest { get; set; }
        /// <summary>
        /// Số lượng duyệt
        /// </summary>
        public double? QuantityApproved { get; set; }
        public int? StatusPurchase { get; set; }       
        public double? QuantityPurchased { get; set; }
        public string Note { get; set; }
        /// <summary>
        /// Thứ tự
        /// </summary>
        public int? DisplayOrder { get; set; }
        public string BidUsername { get; set; }
        public  OrderProduct OrderProduct { get; set; }
        public  RequestPurchase RequestPurchase { get; set; }
    }
}