// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class ReturnOrder : Entity, IAggregateRoot
    {
        public ReturnOrder()
        {
            PaymentInvoice = new HashSet<PaymentInvoice>();
            ReturnOrderProduct = new HashSet<ReturnOrderProduct>();
        }

        public string Code { get; set; }
        public Guid? CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Guid? OrderId { get; set; }
        public string OrderCode { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        /// <summary>
        /// Kho
        /// </summary>
        public Guid? WarehouseId { get; set; }
        /// <summary>
        /// Kho
        /// </summary>
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public DateTime? ReturnDate { get; set; }
        public Guid? AccountId { get; set; }
        public string AccountName { get; set; }
        public Guid? CurrencyId { get; set; }
        public string Currency { get; set; }
        public string Calculation { get; set; }
        public string CurrencyName { get; set; }
        public decimal? ExchangeRate { get; set; }
        public int? TypeDiscount { get; set; }
        public double? DiscountRate { get; set; }
        public int? TypeCriteria { get; set; }
        public decimal? AmountDiscount { get; set; }
        public int? PaymentStatus { get; set; }
        public Guid? ApproveBy { get; set; }
        public DateTime? ApproveDate { get; set; }
        public string ApproveComment { get; set; }
        public string ApproveByName { get; set; }
        public string File { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<PaymentInvoice> PaymentInvoice { get; set; }
        public virtual ICollection<ReturnOrderProduct> ReturnOrderProduct { get; set; }
    }
}