// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class ReturnOrderProduct : Entity, IAggregateRoot
    {
        public Guid? ReturnOrderId { get; set; }
        public Guid? OrderProductId { get; set; }
        public Guid ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public decimal? QuantityReturn { get; set; }
        public decimal? UnitPrice { get; set; }
        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitType { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        /// <summary>
        /// Tiền chiết khấu phân bổ
        /// </summary>
        public decimal? DiscountAmountDistribution { get; set; }
        /// <summary>
        /// Loại chiết khấu: 0-Phần trăm, 1-Giá trị
        /// </summary>
        public int? DiscountType { get; set; }
        /// <summary>
        /// % Chiết khấu
        /// </summary>
        public double? DiscountPercent { get; set; }
        /// <summary>
        /// Chiết khấu
        /// </summary>
        public decimal? AmountDiscount { get; set; }
        public double? TaxRate { get; set; }
        public string Tax { get; set; }
        public string TaxCode { get; set; }
        public Guid? ReasonId { get; set; }
        public string ReasonName { get; set; }
        public string WarehouseName { get; set; }
        public Guid? WarehouseId { get; set; }
        public int? DisplayOrder { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  OrderProduct OrderProduct { get; set; }
        public  Reason Reason { get; set; }
        public virtual ReturnOrder ReturnOrder { get; set; }
    }
}