// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class RouteShipping : Entity, IAggregateRoot
    {
        public RouteShipping()
        {
            PriceListCross = new HashSet<PriceListCross>();
            PriceListSurcharge = new HashSet<PriceListSurcharge>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public string Note { get; set; }
        public string FromPost { get; set; }
        public string ToPost { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public  ICollection<PriceListCross> PriceListCross { get; set; }
        public  ICollection<PriceListSurcharge> PriceListSurcharge { get; set; }
    }
}