// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class RptSoChiTietBanHang : Entity, IAggregateRoot
    { 
        public Guid? ReportId { get; set; }
        public string OrderCode { get; set; }
        public DateTime? OrderDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public double? Quantity { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? AmountDiscount { get; set; }
        public double? TaxRate { get; set; }
        public double? ReturnQuantity { get; set; }
        public decimal? ReturnAmount { get; set; }
        public decimal? SaleAmount { get; set; }
        public decimal? Revenue { get; set; }

        public virtual Report Report { get; set; }
    }
}