// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class RptTinhHinhThucHienHopDongBan : Entity, IAggregateRoot
    {
        public Guid? ReportId { get; set; }
        public string Code { get; set; }
        public DateTime? Date { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? QuantitySold { get; set; }
        public decimal? SaleContract { get; set; }
        public decimal? SaleMade { get; set; }

        public virtual Report Report { get; set; }
    }
}