// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class RptTongHopBanHangTheoNhomKhachHang : Entity, IAggregateRoot
    {
        public Guid? ReportId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal? AmountNoDiscount { get; set; }
        public decimal? AmountDiscount { get; set; }
        public decimal? AmountTax { get; set; }
        public double? ReturnQuantity { get; set; }
        public decimal? ReturnAmount { get; set; }
        public decimal? SaleAmount { get; set; }
        public decimal? Revenue { get; set; }

        public virtual Report Report { get; set; }
    }
}