// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class RptTongHopBanHangTheoKhachHangVaDonBanHang : Entity, IAggregateRoot
    {
        public Guid? ReportId { get; set; }
        public Guid? ParentId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string OrderCode { get; set; }
        public DateTime? OrderDate { get; set; }
        public decimal? TotalAmountTax { get; set; }
        public decimal? PaymentAmount { get; set; }

        public virtual Report Report { get; set; }
    }
}