// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class SalesDiscount : Entity, IAggregateRoot
    {
        public SalesDiscount()
        {
            PaymentInvoice = new HashSet<PaymentInvoice>();
            SalesDiscountProduct = new HashSet<SalesDiscountProduct>();
        }

        public string Code { get; set; }
        /// <summary>
        /// Khách hàng
        /// </summary>
        public Guid? CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Guid? CustomerAddressId { get; set; }
        /// <summary>
        /// tham chiếu tới bảng order
        /// </summary>
        public string SalesOrderCode { get; set; }
        public Guid? SalesOrderId { get; set; }
        public Guid? CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public decimal? ExchangeRate { get; set; }
        /// <summary>
        /// Nhân viên
        /// </summary>
        public Guid? EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string Note { get; set; }
        public int? TypeDiscount { get; set; }
        public int? Status { get; set; }
        /// <summary>
        /// Ngày giảm giá
        /// </summary>
        public DateTime? DiscountDate { get; set; }
        public int? PaymentStatus { get; set; }
        public string File { get; set; }
        public Guid? ApproveBy { get; set; }
        public DateTime? ApproveDate { get; set; }
        public string ApproveByName { get; set; }
        public string ApproveComment { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual ICollection<PaymentInvoice> PaymentInvoice { get; set; }
        public virtual ICollection<SalesDiscountProduct> SalesDiscountProduct { get; set; }
    }
}