// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_ACCOUNT_REVENUE_LOADResult
    {
        public Guid? Id { get; set; }
        public decimal? Revenue { get; set; }
        public decimal? RevenueMonth { get; set; }
    }
}
