// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_DB_SALESCHANNEL_SALEResult
    {
        public int Id { get; set; }
        public Guid? ChannelId { get; set; }
        public string ChannelName { get; set; }
        public int? NumberOfOrder { get; set; }
    }
    
    public partial class SP_DB_SALES_PRODUCT_BY_TIME
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
    }

    public partial class SP_DB_CONTRACT
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
    }
    public partial class SP_DB_EMPLOYEE_EXCELLENT
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
    }

    public partial class SP_DB_PAYMENT
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
    }
    
}
