// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_DB_COUNT_CUSTOMERResult
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Title { get; set; }
        public int? Value { get; set; }
    }
}
