// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class StorePriceList : Entity, IAggregateRoot
    {
        public Guid? StoreId { get; set; }
        public Guid? PriceListId { get; set; }
        public string PriceListName { get; set; }
        public bool? Default { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public int? DisplayOrder { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }

        public  PriceList PriceList { get; set; }
        public  Store Store { get; set; }
    }
}