// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.SO.Models
{
    public partial class Wallet : Entity, IAggregateRoot
    {
        public Wallet()
        {
            WalletTransaction = new HashSet<WalletTransaction>();
        }
         
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal? Cash { get; set; }
        public decimal? CashHold { get; set; }
        public decimal? CashHoldBid { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }
        public string Hash { get; set; }

        public  ICollection<WalletTransaction> WalletTransaction { get; set; }
    }
}