// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class BankConfiguration : IEntityTypeConfiguration<Bank>
    {
        public void Configure(EntityTypeBuilder<Bank> entity)
        {
            entity.ToTable("Bank", "so");

            entity.HasComment("Danh mục ngân hàng");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasComment("Mã guid tự sinh của bản ghi");

            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasComment("Địa chỉ (trụ sở chính)");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Mã ngân hàng (tên viết tắt)");

            entity.Property(e => e.CreatedBy).HasComment("");

            entity.Property(e => e.CreatedByName)
                .HasMaxLength(255)
                .HasComment("");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasComment("Ngày giờ tạo");

            entity.Property(e => e.DisplayOrder).HasComment("Thứ tự hiển thị trong danh sách");

            entity.Property(e => e.EnglishName)
                .HasMaxLength(255)
                .HasComment("Tên tiếng anh");

            entity.Property(e => e.Image)
                .HasMaxLength(250)
                .HasComment("Ảnh");

            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasComment("Tên ngân hàng (tên đầy đủ)");

            entity.Property(e => e.Note)
                .HasMaxLength(400)
                .HasComment("Ghi chú/Diễn giải.");

            entity.Property(e => e.Qrbin)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("QRBin");

            entity.Property(e => e.ShortName).HasMaxLength(255);

            entity.Property(e => e.Status)
                .HasComment("Trạng thái. = 0 - Ngừng sử dụng, = 1 - Đang sử dụng");

            entity.Property(e => e.UpdatedBy).HasComment("");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasComment("Ngày giờ sửa");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Bank> entity);
    }
}
