// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CampaignStatusConfiguration : IEntityTypeConfiguration<CampaignStatus>
    {
        public void Configure(EntityTypeBuilder<CampaignStatus> entity)
        {
            entity.ToTable("Campaign_Status", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Color)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.TextColor)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.CreatedByName).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsDefault).HasComment("Bước mặc định");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Status)
            .HasDefaultValueSql("((1))")
            .HasComment("Trạng thái ");
            entity.Property(e => e.UpdatedByName).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Campaign).WithMany(p => p.CampaignStatuses)
            .HasForeignKey(d => d.CampaignId)
            .HasConstraintName("FK_Campaign_Status_Campaign");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CampaignStatus> entity);
    }
}
