// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CouponCustomerGroupConfiguration : IEntityTypeConfiguration<CouponCustomerGroup>
    {
        public void Configure(EntityTypeBuilder<CouponCustomerGroup> entity)
        {
            entity.ToTable("CouponCustomerGroup", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Coupon)
                .WithMany(p => p.CouponCustomerGroup)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CouponCustomerGroup_Coupon");

            entity.HasOne(d => d.CustomerGroup)
                .WithMany(p => p.CouponCustomerGroup)
                .HasForeignKey(d => d.CustomerGroupId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CouponCustomerGroup_CustomerGroup");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CouponCustomerGroup> entity);
    }
}
