// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CouponConfiguration : IEntityTypeConfiguration<Coupon>
    {
        public void Configure(EntityTypeBuilder<Coupon> entity)
        {
            entity.ToTable("Coupon", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.EndDate).HasColumnType("date");

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.SalesChannel)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.StartDate).HasColumnType("date");

            entity.Property(e => e.Stores)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.CouponGroup)
                .WithMany(p => p.Coupon)
                .HasForeignKey(d => d.CouponGroupId)
                .HasConstraintName("FK_Coupon_CouponGroup");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Coupon> entity);
    }
}
