// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CouponCustomerConfiguration : IEntityTypeConfiguration<CouponCustomer>
    {
        public void Configure(EntityTypeBuilder<CouponCustomer> entity)
        {
            entity.ToTable("CouponCustomer", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Coupon)
                .WithMany(p => p.CouponCustomer)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CouponCustomer_Coupon");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CouponCustomer)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CouponCustomer_Customer");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CouponCustomer> entity);
    }
}
