// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CustomerPriceListCrossConfiguration : IEntityTypeConfiguration<CustomerPriceListCross>
    {
        public void Configure(EntityTypeBuilder<CustomerPriceListCross> entity)
        {
            entity.ToTable("CustomerPriceListCross", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.PriceListCrossName).HasMaxLength(150);

            entity.Property(e => e.RouterShipping).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CustomerPriceListCross)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_CustomerPriceListCross_Customer");

            entity.HasOne(d => d.PriceListCross)
                .WithMany(p => p.CustomerPriceListCross)
                .HasForeignKey(d => d.PriceListCrossId)
                .HasConstraintName("FK_CustomerPriceListCross_PriceListCross");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerPriceListCross> entity);
    }
}
