// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> entity)
        {
            entity.ToTable("Customer", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AccountCreatedDate).HasColumnType("datetime");

            entity.Property(e => e.AccountEmail).HasMaxLength(150);

            entity.Property(e => e.AccountPhone)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.AccountUsername)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.Address).HasMaxLength(255);

            entity.Property(e => e.Alias).HasMaxLength(50);

            entity.Property(e => e.Birthday).HasColumnType("datetime");

            entity.Property(e => e.BmapGroup).HasColumnName("BMapGroup");

            entity.Property(e => e.BusinessSector).HasMaxLength(500);

            entity.Property(e => e.Capital).HasColumnType("money");

            entity.Property(e => e.CccdNumber).HasMaxLength(50);

            entity.Property(e => e.Code)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.CompanyName).HasMaxLength(255);

            entity.Property(e => e.CompanyPhone).HasMaxLength(255);

            entity.Property(e => e.CompanySize).HasMaxLength(255);

            entity.Property(e => e.Country).HasMaxLength(50);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Currency)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CurrencyName).HasMaxLength(255);

            entity.Property(e => e.CustomerGroup).HasMaxLength(500);

            entity.Property(e => e.CustomerSourceName).HasMaxLength(250);

            entity.Property(e => e.DateRange).HasColumnType("datetime");

            entity.Property(e => e.DebtLimit).HasColumnType("money");

            entity.Property(e => e.District).HasMaxLength(50);

            entity.Property(e => e.Email).HasMaxLength(255);

            entity.Property(e => e.EstablishedDate).HasColumnType("date");

            entity.Property(e => e.Fax).HasMaxLength(255);

            entity.Property(e => e.IdDate).HasColumnType("datetime");

            entity.Property(e => e.IdImage1).HasMaxLength(255);

            entity.Property(e => e.IdImage2).HasMaxLength(255);

            entity.Property(e => e.IdIssuer).HasMaxLength(250);

            entity.Property(e => e.IdName).HasMaxLength(250);

            entity.Property(e => e.IdNumber).HasMaxLength(50);

            entity.Property(e => e.Image).HasMaxLength(250);

            entity.Property(e => e.IssuedBy).HasMaxLength(250);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.PriceListName).HasMaxLength(150);

            entity.Property(e => e.PriceListPurchaseName).HasMaxLength(150);

            entity.Property(e => e.Province).HasMaxLength(50);

            entity.Property(e => e.RemainingDebt).HasColumnType("money");

            entity.Property(e => e.Representative).HasMaxLength(250);

            entity.Property(e => e.Revenue).HasColumnType("money");

            entity.Property(e => e.RevenueMonth).HasColumnType("money");

            entity.Property(e => e.Tags).HasMaxLength(500);

            entity.Property(e => e.TaxCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Tenant)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Ward).HasMaxLength(50);

            entity.Property(e => e.Website).HasMaxLength(50);

            entity.Property(e => e.ZipCode).HasMaxLength(50);

            entity.HasOne(d => d.CustomerSource)
                .WithMany(p => p.Customer)
                .HasForeignKey(d => d.CustomerSourceId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Customer_CustomerSource");

            entity.HasOne(d => d.GroupEmployee)
                .WithMany(p => p.Customer)
                .HasForeignKey(d => d.GroupEmployeeId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Customer_GroupEmployee");

            entity.HasOne(d => d.PriceListPurchase)
                .WithMany(p => p.Customer)
                .HasForeignKey(d => d.PriceListPurchaseId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Customer_PriceListPurchase");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customer> entity);
    }
}
