// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CustomerBankConfiguration : IEntityTypeConfiguration<CustomerBank>
    {
        public void Configure(EntityTypeBuilder<CustomerBank> entity)
        {
            entity.ToTable("CustomerBank", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AccountName).HasMaxLength(255);

            entity.Property(e => e.AccountNumber).HasMaxLength(50);

            entity.Property(e => e.BankBranch).HasMaxLength(255);

            entity.Property(e => e.BankCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.BankName).HasMaxLength(255);

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Default).HasComment("Địa chỉ giao hàng mặc định");

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CustomerBank)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_CustomerBank_Customer");

            entity.HasOne(d => d.Employee).WithMany(p => p.CustomerBanks)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CustomerBank_Employee");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerBank> entity);
    }
}
