// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CustomerBusinessMappingConfiguration : IEntityTypeConfiguration<CustomerBusinessMapping>
    {
        public void Configure(EntityTypeBuilder<CustomerBusinessMapping> entity)
        {
            entity.ToTable("CustomerBusiness_Mapping", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Business)
                .WithMany(p => p.CustomerBusinessMapping)
                .HasForeignKey(d => d.BusinessId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerBusiness_Mapping_Business");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CustomerBusinessMapping)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_CustomerBusiness_Mapping_Customer");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerBusinessMapping> entity);
    }
}
