// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class CustomerAddressConfiguration : IEntityTypeConfiguration<CustomerAddress>
    {
        public void Configure(EntityTypeBuilder<CustomerAddress> entity)
        {
            entity.ToTable("CustomerAddress", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Address).HasMaxLength(255);

            entity.Property(e => e.BillingDefault).HasComment("Địa chỉ xuất hóa đơn mặc định");

            entity.Property(e => e.Country).HasMaxLength(50);

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.District).HasMaxLength(50);

            entity.Property(e => e.Email).HasMaxLength(255);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.Note).HasMaxLength(400);

            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Province).HasMaxLength(50);

            entity.Property(e => e.ShippingDefault).HasComment("Địa chỉ giao hàng mặc định");

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Ward).HasMaxLength(50);

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CustomerAddress)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_CustomerAddress_Customer");

            entity.HasOne(d => d.Employee).WithMany(p => p.CustomerAddresses)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CustomerAddress_Employee");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerAddress> entity);
    }
}
