// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class ExchangeRateConfiguration : IEntityTypeConfiguration<ExchangeRate>
    {
        public void Configure(EntityTypeBuilder<ExchangeRate> entity)
        {
            entity.ToTable("ExchangeRate", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.ActiveDate).HasColumnType("datetime");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Rate).HasColumnType("money");

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Currency)
                .WithMany(p => p.ExchangeRate)
                .HasForeignKey(d => d.CurrencyId)
                .HasConstraintName("FK_ExchangeRate_Currency");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ExchangeRate> entity);
    }
}
