// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class ExportProductConfiguration : IEntityTypeConfiguration<ExportProduct>
    {
        public void Configure(EntityTypeBuilder<ExportProduct> entity)
        {
            entity.ToTable("ExportProduct", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedByName).HasMaxLength(150);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Note).HasMaxLength(1000);
            entity.Property(e => e.Origin).HasMaxLength(250);
            entity.Property(e => e.ProductCode)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.ProductImage).HasMaxLength(250);
            entity.Property(e => e.ProductName).HasMaxLength(250);
            entity.Property(e => e.UnitCode)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasComment("Đơn vị tính");
            entity.Property(e => e.UnitName).HasMaxLength(50);
            entity.Property(e => e.UnitType)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.UpdatedByName).HasMaxLength(150);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Export).WithMany(p => p.ExportProducts)
            .HasForeignKey(d => d.ExportId)
            .HasConstraintName("FK_ExportProduct_Export");

            entity.HasOne(d => d.ExportWarehouseProduct).WithMany(p => p.ExportProducts)
            .HasForeignKey(d => d.ExportWarehouseProductId)
            .HasConstraintName("FK_ExportProduct_ExportWarehouseProduct");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ExportProduct> entity);
    }
}
