// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class ExportConfiguration : IEntityTypeConfiguration<Export>
    {
        public void Configure(EntityTypeBuilder<Export> entity)
        {
            entity.ToTable("Export", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApproveByName).HasMaxLength(250);
            entity.Property(e => e.ApproveComment).HasMaxLength(1000);
            entity.Property(e => e.ApproveDate).HasColumnType("datetime");
            entity.Property(e => e.Code)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasComment("Số phiếu");
            entity.Property(e => e.CreatedByName).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EmployeeCode)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.EmployeeId).HasComment("Người phụ trách");
            entity.Property(e => e.EmployeeName).HasMaxLength(250);
            entity.Property(e => e.ExportDate)
            .HasComment("Ngày xuất kho")
            .HasColumnType("datetime");
            entity.Property(e => e.Note).HasMaxLength(1000);
            entity.Property(e => e.Status).HasComment("Trạng thái :1#Chờ xử lý;2#Đã xuất khẩu");
            entity.Property(e => e.UpdatedByName).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.ExportWarehouse).WithMany(p => p.Exports)
            .HasForeignKey(d => d.ExportWarehouseId)
            .HasConstraintName("FK_Export_ExportWarehouse");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Export> entity);
    }
}
