// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class GroupEmployeeMappingConfiguration : IEntityTypeConfiguration<GroupEmployeeMapping>
    {
        public void Configure(EntityTypeBuilder<GroupEmployeeMapping> entity)
        {
            entity.ToTable("GroupEmployee_Mapping", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Employee)
                .WithMany(p => p.GroupEmployeeMapping)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_GroupEmployee_Mapping_Employee");

            entity.HasOne(d => d.GroupEmployee)
                .WithMany(p => p.GroupEmployeeMapping)
                .HasForeignKey(d => d.GroupEmployeeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_GroupEmployee_Mapping_GroupEmployee");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GroupEmployeeMapping> entity);
    }
}
