// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class LeadConfiguration : IEntityTypeConfiguration<Lead>
    {
        public void Configure(EntityTypeBuilder<Lead> entity)
        {
            entity.ToTable("Lead", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.BusinessSector).HasMaxLength(500);
            entity.Property(e => e.Capital).HasColumnType("money");
            entity.Property(e => e.Code).HasMaxLength(500);
            entity.Property(e => e.Company).HasMaxLength(255);
            entity.Property(e => e.CompanyName).HasMaxLength(255);
            entity.Property(e => e.CompanyPhone).HasMaxLength(255);
            entity.Property(e => e.CompanySize).HasMaxLength(255);
            entity.Property(e => e.Country).HasMaxLength(255);
            entity.Property(e => e.CreatedByName).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerCode)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Demand).HasMaxLength(500);
            entity.Property(e => e.District).HasMaxLength(255);
            entity.Property(e => e.DynamicData).HasColumnType("ntext");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Employee).HasMaxLength(250);
            entity.Property(e => e.EstablishedDate).HasColumnType("date");
            entity.Property(e => e.Facebook).HasMaxLength(50);
            entity.Property(e => e.Group).HasMaxLength(250);
            entity.Property(e => e.GroupEmployee).HasMaxLength(250);
            entity.Property(e => e.Image).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.Phone)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.Phone1)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.Phone2)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.Province).HasMaxLength(255);
            entity.Property(e => e.RevenueTarget).HasColumnType("money");
            entity.Property(e => e.Scale).HasMaxLength(250);
            entity.Property(e => e.Source).HasMaxLength(255);
            entity.Property(e => e.Tags).HasMaxLength(500);
            entity.Property(e => e.TaxCode).HasMaxLength(255);
            entity.Property(e => e.UpdatedByName).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Ward).HasMaxLength(255);
            entity.Property(e => e.Website).HasMaxLength(255);
            entity.Property(e => e.Zalo).HasMaxLength(50);
            entity.Property(e => e.ZipCode).HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Lead> entity);
    }
}
