// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class LeadCampaignConfiguration : IEntityTypeConfiguration<LeadCampaign>
    {
        public void Configure(EntityTypeBuilder<LeadCampaign> entity)
        {
            entity.ToTable("Lead_Campaign", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Campaign).HasMaxLength(250);
            entity.Property(e => e.CreatedByName).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(250);
            entity.Property(e => e.LeaderName).HasMaxLength(50);
            entity.Property(e => e.Member).HasMaxLength(2000);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(250);
            entity.Property(e => e.State)
            .HasMaxLength(250)
            .HasComment("Bước chăm sóc");
            entity.Property(e => e.UpdatedByName).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.CampaignNavigation).WithMany(p => p.LeadCampaigns)
            .HasForeignKey(d => d.CampaignId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_Lead_Campaign_Campaign");

            entity.HasOne(d => d.Lead).WithMany(p => p.LeadCampaigns)
            .HasForeignKey(d => d.LeadId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_Lead_Campaign_Lead");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LeadCampaign> entity);
    }
}
