// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class LeadTopicSuggestConfiguration : IEntityTypeConfiguration<LeadTopicSuggest>
    {
        public void Configure(EntityTypeBuilder<LeadTopicSuggest> entity)
        {
            entity.ToTable("LeadTopicSuggest", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedByName).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Page).HasMaxLength(50);
            entity.Property(e => e.Topic).HasMaxLength(50);
            entity.Property(e => e.UpdatedByName).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Lead).WithMany(p => p.LeadTopicSuggests)
            .HasForeignKey(d => d.LeadId)
            .HasConstraintName("FK_LeadTopicSuggest_Lead");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LeadTopicSuggest> entity);
    }
}
