// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class LeadActivityConfiguration : IEntityTypeConfiguration<LeadActivity>
    {
        public void Configure(EntityTypeBuilder<LeadActivity> entity)
        {
            entity.ToTable("LeadActivity", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ActualDate).HasColumnType("datetime");
            entity.Property(e => e.Attachment).HasMaxLength(500);
            entity.Property(e => e.Body).HasColumnType("ntext");
            entity.Property(e => e.Campaign).HasMaxLength(250);
            entity.Property(e => e.CreatedByName).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Type)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasComment("CALL, EMAIL, CHAT, TASK, EVENT");
            entity.Property(e => e.UpdatedByName).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Lead).WithMany(p => p.LeadActivities)
            .HasForeignKey(d => d.LeadId)
            .HasConstraintName("FK_LeadActivity_Lead");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LeadActivity> entity);
    }
}
