// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class OrderServiceAddConfiguration : IEntityTypeConfiguration<OrderServiceAdd>
    {
        public void Configure(EntityTypeBuilder<OrderServiceAdd> entity)
        {
            entity.ToTable("OrderServiceAdd", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Calculation)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('*')");

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Currency)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ExchangeRate).HasColumnType("decimal(18, 10)");

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.Price).HasColumnType("money");

            entity.Property(e => e.ServiceAddName).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.OrderExpress)
                .WithMany(p => p.OrderServiceAdd)
                .HasForeignKey(d => d.OrderExpressId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_OrderServiceAdd_OrderExpress");

            entity.HasOne(d => d.Order)
                .WithMany(p => p.OrderServiceAdd)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_OrderServiceAdd_Order");

            entity.HasOne(d => d.Quotation)
                .WithMany(p => p.OrderServiceAdd)
                .HasForeignKey(d => d.QuotationId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_OrderServiceAdd_Quotation");

            entity.HasOne(d => d.ServiceAdd)
                .WithMany(p => p.OrderServiceAdd)
                .HasForeignKey(d => d.ServiceAddId)
                .HasConstraintName("FK_OrderServiceAdd_ServiceAdd");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderServiceAdd> entity);
    }
}
