// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class OrderFulfillmentConfiguration : IEntityTypeConfiguration<OrderFulfillment>
    {
        public void Configure(EntityTypeBuilder<OrderFulfillment> entity)
        {
            entity.ToTable("OrderFulfillment", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AccountName).HasMaxLength(255);

            entity.Property(e => e.ChannelName).HasMaxLength(255);

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ContractName).HasMaxLength(255);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(255);

            entity.Property(e => e.GroupEmployeeName).HasMaxLength(255);

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.OrderDate).HasColumnType("datetime");

            entity.Property(e => e.PickupAddress).HasMaxLength(250);

            entity.Property(e => e.PickupCountry).HasMaxLength(250);

            entity.Property(e => e.PickupDistrict).HasMaxLength(250);

            entity.Property(e => e.PickupName).HasMaxLength(250);

            entity.Property(e => e.PickupNote).HasMaxLength(500);

            entity.Property(e => e.PickupPhone).HasMaxLength(250);

            entity.Property(e => e.PickupProvince).HasMaxLength(250);

            entity.Property(e => e.PickupWard).HasMaxLength(250);

            entity.Property(e => e.PickupZipCode).HasMaxLength(250);

            entity.Property(e => e.ShipperAddress).HasMaxLength(250);

            entity.Property(e => e.ShipperCountry).HasMaxLength(250);

            entity.Property(e => e.ShipperDistrict).HasMaxLength(250);

            entity.Property(e => e.ShipperName).HasMaxLength(250);

            entity.Property(e => e.ShipperNote).HasMaxLength(500);

            entity.Property(e => e.ShipperPhone).HasMaxLength(250);

            entity.Property(e => e.ShipperProvince).HasMaxLength(250);

            entity.Property(e => e.ShipperWard).HasMaxLength(250);

            entity.Property(e => e.ShipperZipCode).HasMaxLength(250);

            entity.Property(e => e.StoreCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.StoreName).HasMaxLength(255);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderFulfillment> entity);
    }
}
