// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class OrderInvoiceConfiguration : IEntityTypeConfiguration<OrderInvoice>
    {
        public void Configure(EntityTypeBuilder<OrderInvoice> entity)
        {
            entity.ToTable("OrderInvoice", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Date).HasColumnType("datetime");

            entity.Property(e => e.Note).HasMaxLength(1000);

            entity.Property(e => e.Number)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.OrderCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Serial).HasMaxLength(250);

            entity.Property(e => e.Symbol).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Value).HasColumnType("decimal(18, 5)");

            entity.HasOne(d => d.Order)
                .WithMany(p => p.OrderInvoice)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderInvoice_Order");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderInvoice> entity);
    }
}
