// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class OrderExpressConfiguration : IEntityTypeConfiguration<OrderExpress>
    {
        public void Configure(EntityTypeBuilder<OrderExpress> entity)
        {
            entity.ToTable("OrderExpress", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AccountName).HasMaxLength(255);

            entity.Property(e => e.AirFreight).HasColumnType("money");

            entity.Property(e => e.BillAddress).HasMaxLength(250);

            entity.Property(e => e.BillCountry).HasMaxLength(250);

            entity.Property(e => e.BillDistrict).HasMaxLength(250);

            entity.Property(e => e.BillName).HasMaxLength(250);

            entity.Property(e => e.BillProvince).HasMaxLength(250);

            entity.Property(e => e.BillWard).HasMaxLength(250);

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CommodityGroup)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ContractName).HasMaxLength(255);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Currency)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(255);

            entity.Property(e => e.DeliveryAddress).HasMaxLength(250);

            entity.Property(e => e.DeliveryCountry).HasMaxLength(250);

            entity.Property(e => e.DeliveryDistrict).HasMaxLength(250);

            entity.Property(e => e.DeliveryMethodCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DeliveryMethodName).HasMaxLength(255);

            entity.Property(e => e.DeliveryName).HasMaxLength(250);

            entity.Property(e => e.DeliveryNote).HasMaxLength(500);

            entity.Property(e => e.DeliveryPhone).HasMaxLength(250);

            entity.Property(e => e.DeliveryProvince).HasMaxLength(250);

            entity.Property(e => e.DeliveryWard).HasMaxLength(250);

            entity.Property(e => e.DeliveryZipCode).HasMaxLength(250);

            entity.Property(e => e.Description).HasMaxLength(1000);

            entity.Property(e => e.DomesticCarrier).HasMaxLength(250);

            entity.Property(e => e.DomesticTracking)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.EstimatedDeliveryDate).HasColumnType("datetime");

            entity.Property(e => e.ExchangeRate).HasColumnType("decimal(18, 10)");

            entity.Property(e => e.GroupEmployeeName).HasMaxLength(255);

            entity.Property(e => e.Image).HasMaxLength(255);

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.OrderDate).HasColumnType("datetime");

            entity.Property(e => e.OrderType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Paid).HasColumnType("money");

            entity.Property(e => e.PaymentMethodId).HasComment("Điều khoản thanh toán");

            entity.Property(e => e.PaymentMethodName).HasMaxLength(255);

            entity.Property(e => e.PaymentTermName).HasMaxLength(255);

            entity.Property(e => e.RouterShipping).HasMaxLength(250);

            entity.Property(e => e.SeaFreight).HasColumnType("money");

            entity.Property(e => e.ShipperAddress).HasMaxLength(250);

            entity.Property(e => e.ShipperCountry).HasMaxLength(250);

            entity.Property(e => e.ShipperDistrict).HasMaxLength(250);

            entity.Property(e => e.ShipperName).HasMaxLength(250);

            entity.Property(e => e.ShipperNote).HasMaxLength(500);

            entity.Property(e => e.ShipperPhone).HasMaxLength(250);

            entity.Property(e => e.ShipperProvince).HasMaxLength(250);

            entity.Property(e => e.ShipperWard).HasMaxLength(250);

            entity.Property(e => e.ShipperZipCode).HasMaxLength(250);

            entity.Property(e => e.ShippingMethodCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ShippingMethodName).HasMaxLength(255);

            entity.Property(e => e.StoreCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.StoreName).HasMaxLength(255);

            entity.Property(e => e.Surcharge).HasColumnType("money");

            entity.Property(e => e.Total).HasColumnType("money");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");


            entity.Property(e => e.TrackingCode)
                .HasMaxLength(255)
                .IsUnicode(true);

            entity.Property(e => e.TrackingCarrier)
                .HasMaxLength(255)
                .IsUnicode(true);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderExpress> entity);
    }
}
