// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class OrderFulfillmentDetailConfiguration : IEntityTypeConfiguration<OrderFulfillmentDetail>
    {
        public void Configure(EntityTypeBuilder<OrderFulfillmentDetail> entity)
        {
            entity.ToTable("OrderFulfillmentDetail", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Note).HasMaxLength(1000);

            entity.Property(e => e.Origin).HasMaxLength(250);

            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductImage).HasMaxLength(250);

            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.Property(e => e.UnitPrice)
                .HasColumnType("money")
                .HasComment("Đơn giá");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.WarehouseCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.WarehouseName).HasMaxLength(255);

            entity.HasOne(d => d.OrderFulfillment)
                .WithMany(p => p.OrderFulfillmentDetail)
                .HasForeignKey(d => d.OrderFulfillmentId)
                .HasConstraintName("FK_OrderFulfillmentDetail_OrderFulfillment");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderFulfillmentDetail> entity);
    }
}
