// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class OrderCostConfiguration : IEntityTypeConfiguration<OrderCost>
    {
        public void Configure(EntityTypeBuilder<OrderCost> entity)
        {
            entity.ToTable("OrderCost", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Amount).HasColumnType("money");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Expense)
                .WithMany(p => p.OrderCost)
                .HasForeignKey(d => d.ExpenseId)
                .HasConstraintName("FK_OrderCost_Expense");

            entity.HasOne(d => d.Order)
                .WithMany(p => p.OrderCost)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_OrderCost_Order");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderCost> entity);
    }
}
