// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PriceListSurchargeConfiguration : IEntityTypeConfiguration<PriceListSurcharge>
    {
        public void Configure(EntityTypeBuilder<PriceListSurcharge> entity)
        {
            entity.ToTable("PriceListSurcharge", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Currency)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.Price).HasColumnType("money");

            entity.Property(e => e.RouterShipping).HasMaxLength(250);

            entity.Property(e => e.SurchargeGroup).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.RouterShippingNavigation)
                .WithMany(p => p.PriceListSurcharge)
                .HasForeignKey(d => d.RouterShippingId)
                .HasConstraintName("FK_PriceListSurcharge_RouteShipping");

            entity.HasOne(d => d.SurchargeGroupNavigation)
                .WithMany(p => p.PriceListSurcharge)
                .HasForeignKey(d => d.SurchargeGroupId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PriceListSurcharge_SurchargeGroup");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PriceListSurcharge> entity);
    }
}
