// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PriceListDetailConfiguration : IEntityTypeConfiguration<PriceListDetail>
    {
        public void Configure(EntityTypeBuilder<PriceListDetail> entity)
        {
            entity.ToTable("PriceListDetail", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CurrencyName).HasMaxLength(255);

            entity.Property(e => e.DiscountValue).HasColumnType("money");

            entity.Property(e => e.FixPrice).HasColumnType("money");

            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductName).HasMaxLength(400);

            entity.Property(e => e.QuantityMin).HasDefaultValueSql("((1))");

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Đơn vị tính");

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.Property(e => e.UnitType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Đơn vị tính");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.PriceList)
                .WithMany(p => p.PriceListDetail)
                .HasForeignKey(d => d.PriceListId)
                .HasConstraintName("FK_PriceListDetail_PriceList");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PriceListDetail> entity);
    }
}
