// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PriceListCrossConfiguration : IEntityTypeConfiguration<PriceListCross>
    {
        public void Configure(EntityTypeBuilder<PriceListCross> entity)
        {
            entity.ToTable("PriceListCross", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Description).HasMaxLength(1000);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.RouterShipping).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.RouterShippingNavigation)
                .WithMany(p => p.PriceListCross)
                .HasForeignKey(d => d.RouterShippingId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PriceListCross_RouteShipping1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PriceListCross> entity);
    }
}
