// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PriceListPurchaseDetailConfiguration : IEntityTypeConfiguration<PriceListPurchaseDetail>
    {
        public void Configure(EntityTypeBuilder<PriceListPurchaseDetail> entity)
        {
            entity.ToTable("PriceListPurchaseDetail", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.BuyFeeFix).HasColumnType("money");

            entity.Property(e => e.BuyFeeMin).HasColumnType("money");

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Currency)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.PriceListPurchase).HasMaxLength(255);

            entity.Property(e => e.PurchaseGroupCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.PurchaseGroupName).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.PriceListPurchaseNavigation)
                .WithMany(p => p.PriceListPurchaseDetail)
                .HasForeignKey(d => d.PriceListPurchaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceListPurchaseDetail_PriceListPurchase");

            entity.HasOne(d => d.PurchaseGroup)
                .WithMany(p => p.PriceListPurchaseDetail)
                .HasForeignKey(d => d.PurchaseGroupId)
                .HasConstraintName("FK_PriceListPurchase_PurchaseGroup");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PriceListPurchaseDetail> entity);
    }
}
