// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PriceListCrossDetailConfiguration : IEntityTypeConfiguration<PriceListCrossDetail>
    {
        public void Configure(EntityTypeBuilder<PriceListCrossDetail> entity)
        {
            entity.ToTable("PriceListCrossDetail", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AirFreight).HasColumnType("money");

            entity.Property(e => e.CommodityGroupCode).HasMaxLength(250);

            entity.Property(e => e.CommodityGroupName).HasMaxLength(250);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Currency)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.PriceListCross).HasMaxLength(255);

            entity.Property(e => e.SeaFreight).HasColumnType("money");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.CommodityGroup)
                .WithMany(p => p.PriceListCrossDetail)
                .HasForeignKey(d => d.CommodityGroupId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PriceListCross_CommodityGroup");

            entity.HasOne(d => d.PriceListCrossNavigation)
                .WithMany(p => p.PriceListCrossDetail)
                .HasForeignKey(d => d.PriceListCrossId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceListCrossDetail_PriceListCross");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PriceListCrossDetail> entity);
    }
}
