// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class ProductionOrdersDetailConfiguration : IEntityTypeConfiguration<ProductionOrdersDetail>
    {
        public void Configure(EntityTypeBuilder<ProductionOrdersDetail> entity)
        {
            entity.ToTable("ProductionOrdersDetail", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CancelReason).HasMaxLength(500);

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.DeliveryDate).HasColumnType("datetime");

            entity.Property(e => e.EstimateStatus).HasComment("Trạng thái dự toán. 1: Chưa dự toán. 2. Đang dự toán. 3. Đã dự toán");

            entity.Property(e => e.EstimatedDate).HasColumnType("datetime");

            entity.Property(e => e.Gtin)
                .HasMaxLength(150)
                .HasComment("GTIN (global trade item number)");

            entity.Property(e => e.Height).HasComment("Cao");

            entity.Property(e => e.IsEstimated).HasComment("Trạng thái đã dự toán");

            entity.Property(e => e.IsWorkOrdered).HasComment("Trạng thái đã lập lệnh sản xuất");

            entity.Property(e => e.Length).HasComment("Chieu dai");

            entity.Property(e => e.Note).HasMaxLength(250);

            entity.Property(e => e.Origin).HasMaxLength(250);

            entity.Property(e => e.Package).HasComment("So luong/kien");

            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductImage).HasMaxLength(250);

            entity.Property(e => e.ProductName).HasMaxLength(250);

            entity.Property(e => e.ProductionOrdersCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Sku)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Solution)
                .HasMaxLength(500)
                .HasComment("Phuong phap");

            entity.Property(e => e.Status).HasComment("Chờ lập lệnh sx:1, Đang sx: 2, Hoàn thành: 3, Hủy sx: 4");

            entity.Property(e => e.Transport)
                .HasMaxLength(500)
                .HasComment("Van chuyen");

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Đơn vị tính");

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.Property(e => e.UnitType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Volume).HasComment("the tich");

            entity.Property(e => e.Weight).HasComment("Can nang");

            entity.Property(e => e.Width).HasComment("Chieu rong");

            entity.HasOne(d => d.ProductionOrder)
                .WithMany(p => p.ProductionOrdersDetail)
                .HasForeignKey(d => d.ProductionOrdersId)
                .HasConstraintName("FK_ProductionOrdersDetail_ProductionOrdersDetail");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductionOrdersDetail> entity);
    }
}
