// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class ProductionOrderConfiguration : IEntityTypeConfiguration<ProductionOrder>
    {
        public void Configure(EntityTypeBuilder<ProductionOrder> entity)
        {
            entity.ToTable("ProductionOrder", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.CreatedByName).HasMaxLength(250);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerCode)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.CustomerName).HasMaxLength(250);
            entity.Property(e => e.DateNeed).HasColumnType("datetime");
            entity.Property(e => e.EmployeeCode)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.EmployeeName).HasMaxLength(250);
            entity.Property(e => e.EstimateDate)
            .HasComment("Hạn dự toán")
            .HasColumnType("datetime");
            entity.Property(e => e.OrderNumber)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.RequestDate).HasColumnType("datetime");
            entity.Property(e => e.SaleEmployeeCode)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.SaleEmployeeName).HasMaxLength(250);
            entity.Property(e => e.Status).HasComment("1. chờ xử lý, 2 xác nhận, 3 hoàn thành");
            entity.Property(e => e.Type).HasComment("Loại phiếu/ 1: Yêu cầu dự toán, 2: Yêu cầu sản xuất");
            entity.Property(e => e.UpdatedByName).HasMaxLength(250);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductionOrder> entity);
    }
}
