// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PromotionProductBuyConfiguration : IEntityTypeConfiguration<PromotionProductBuy>
    {
        public void Configure(EntityTypeBuilder<PromotionProductBuy> entity)
        {
            entity.ToTable("PromotionProductBuy", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductName).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.PromotionByValue)
                .WithMany(p => p.PromotionProductBuy)
                .HasForeignKey(d => d.PromotionByValueId)
                .HasConstraintName("FK_PromotionProductBuy_PromotionByValue");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PromotionProductBuy> entity);
    }
}
