// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PromotionCustomerGroupConfiguration : IEntityTypeConfiguration<PromotionCustomerGroup>
    {
        public void Configure(EntityTypeBuilder<PromotionCustomerGroup> entity)
        {
            entity.ToTable("PromotionCustomerGroup", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.CustomerGroup)
                .WithMany(p => p.PromotionCustomerGroup)
                .HasForeignKey(d => d.CustomerGroupId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PromotionCustomerGroup_CustomerGroup");

            entity.HasOne(d => d.Promotion)
                .WithMany(p => p.PromotionCustomerGroup)
                .HasForeignKey(d => d.PromotionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PromotionCustomerGroup_Promotion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PromotionCustomerGroup> entity);
    }
}
