// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class PromotionByValueConfiguration : IEntityTypeConfiguration<PromotionByValue>
    {
        public void Configure(EntityTypeBuilder<PromotionByValue> entity)
        {
            entity.ToTable("PromotionByValue", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.FixPrice).HasColumnType("money");

            entity.Property(e => e.LimitTotalValue).HasColumnType("money");

            entity.Property(e => e.MinOrderPrice).HasColumnType("money");

            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductName).HasMaxLength(250);

            entity.Property(e => e.ReduceAmount).HasColumnType("money");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Promotion)
                .WithMany(p => p.PromotionByValue)
                .HasForeignKey(d => d.PromotionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PromotionByValue_Promotion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PromotionByValue> entity);
    }
}
