// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class ReportConfiguration : IEntityTypeConfiguration<Report>
    {
        public void Configure(EntityTypeBuilder<Report> entity)
        {
            entity.ToTable("Report", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CategoryRootId)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.CategoryRootName).HasMaxLength(1000);

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.CustomerId)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(2000);

            entity.Property(e => e.CustomerGroupCode)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.CustomerGroupId)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.CustomerGroupName).HasMaxLength(2000);

            entity.Property(e => e.EmployeeCode)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.EmployeeId)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.EmployeeName).HasMaxLength(1000);

            entity.Property(e => e.FromDate).HasColumnType("date");

            entity.Property(e => e.LoadDate).HasColumnType("datetime");

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.ProductCode)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.ProductId)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.ProductName).HasMaxLength(2000);

            entity.Property(e => e.ReportTypeCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ToDate).HasColumnType("date");

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.ReportType)
                .WithMany(p => p.Report)
                .HasForeignKey(d => d.ReportTypeId)
                .HasConstraintName("FK_Report_ReportType");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Report> entity);
    }
}
