// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RequestPurchaseConfiguration : IEntityTypeConfiguration<RequestPurchase>
    {
        public void Configure(EntityTypeBuilder<RequestPurchase> entity)
        {
            entity.ToTable("RequestPurchase", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.ApproveByName).HasMaxLength(150);

            entity.Property(e => e.ApproveComment).HasMaxLength(1000);

            entity.Property(e => e.ApproveDate).HasColumnType("datetime");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Số đề nghị");

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CurrencyName).HasMaxLength(50);

            entity.Property(e => e.ExchangeRate)
                .HasColumnType("numeric(20, 2)")
                .HasComment("Tỷ giá");

            entity.Property(e => e.File).HasColumnType("ntext");

            entity.Property(e => e.Note).HasMaxLength(1000);

            entity.Property(e => e.OrderCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Số đề nghị PO");

            entity.Property(e => e.Podate)
                .HasColumnType("datetime")
                .HasColumnName("PODate");

            entity.Property(e => e.Postatus).HasColumnName("POStatus");

            entity.Property(e => e.Proposal)
                .HasMaxLength(1000)
                .HasComment("Mục đích đề nghị");

            entity.Property(e => e.PurchaseRequestCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Số đề nghị PO");

            entity.Property(e => e.QuantityApproved).HasComment("Số lượng duyệt");

            entity.Property(e => e.QuantityRequest).HasComment("Số lượng đề nghị");

            entity.Property(e => e.RequestByEmail).HasMaxLength(150);

            entity.Property(e => e.RequestByName).HasMaxLength(150);

            entity.Property(e => e.RequestDate).HasColumnType("datetime");

            entity.Property(e => e.Status).HasComment("Trạng thái: 1-Sử dụng, 0-Không sử dụng");

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RequestPurchase> entity);
    }
}
