// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RequestQuoteConfiguration : IEntityTypeConfiguration<RequestQuote>
    {
        public void Configure(EntityTypeBuilder<RequestQuote> entity)
        {
            entity.ToTable("RequestQuote", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Address).HasMaxLength(255);

            entity.Property(e => e.ChannelCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ChannelName).HasMaxLength(50);

            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(255);

            entity.Property(e => e.DueDate).HasColumnType("datetime");

            entity.Property(e => e.Email).HasMaxLength(255);

            entity.Property(e => e.EmployeeName).HasMaxLength(255);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.Note).HasMaxLength(255);

            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.RequestDate).HasColumnType("datetime");

            entity.Property(e => e.StoreCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.StoreName).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Channel)
                .WithMany(p => p.RequestQuote)
                .HasForeignKey(d => d.ChannelId)
                .HasConstraintName("FK_RequestQuote_RequestQuote");

            entity.HasOne(d => d.Store)
                .WithMany(p => p.RequestQuote)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_RequestQuote_Store");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RequestQuote> entity);
    }
}
