// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class ReturnOrderProductConfiguration : IEntityTypeConfiguration<ReturnOrderProduct>
    {
        public void Configure(EntityTypeBuilder<ReturnOrderProduct> entity)
        {
            entity.ToTable("ReturnOrderProduct", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AmountDiscount)
                .HasColumnType("money")
                .HasComment("Chiết khấu");

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.DiscountAmountDistribution)
                .HasColumnType("money")
                .HasComment("Tiền chiết khấu phân bổ");

            entity.Property(e => e.DiscountPercent).HasComment("% Chiết khấu");

            entity.Property(e => e.DiscountType).HasComment("Loại chiết khấu: 0-Phần trăm, 1-Giá trị");

            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.ReasonName).HasMaxLength(250);

            entity.Property(e => e.Tax).HasMaxLength(150);

            entity.Property(e => e.TaxCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Đơn vị tính");

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.Property(e => e.UnitPrice).HasColumnType("money");

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.WarehouseName).HasMaxLength(250);

            entity.HasOne(d => d.OrderProduct)
                .WithMany(p => p.ReturnOrderProduct)
                .HasForeignKey(d => d.OrderProductId)
                .HasConstraintName("FK_ReturnOrderProduct_OrderProduct");

            entity.HasOne(d => d.Reason)
                .WithMany(p => p.ReturnOrderProduct)
                .HasForeignKey(d => d.ReasonId)
                .HasConstraintName("FK_ReturnOrderProduct_Reason");

            entity.HasOne(d => d.ReturnOrder)
                .WithMany(p => p.ReturnOrderProduct)
                .HasForeignKey(d => d.ReturnOrderId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ReturnOrderProduct_ReturnOrder");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReturnOrderProduct> entity);
    }
}
