// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RptSoChiTietBanHangConfiguration : IEntityTypeConfiguration<RptSoChiTietBanHang>
    {
        public void Configure(EntityTypeBuilder<RptSoChiTietBanHang> entity)
        {
            entity.ToTable("Rpt_SoChiTietBanHang", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AmountDiscount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(400);

            entity.Property(e => e.OrderCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.OrderDate).HasColumnType("datetime");

            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductName).HasMaxLength(250);

            entity.Property(e => e.ReturnAmount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 5)");

            entity.HasOne(d => d.Report)
                .WithMany(p => p.RptSoChiTietBanHang)
                .HasForeignKey(d => d.ReportId)
                .HasConstraintName("FK_Rpt_SoChiTietBanHang_Report");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RptSoChiTietBanHang> entity);
    }
}
