// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models; 
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RptTongHopBanHangTheoKhachHangConfiguration : IEntityTypeConfiguration<RptTongHopBanHangTheoKhachHang>
    {
        public void Configure(EntityTypeBuilder<RptTongHopBanHangTheoKhachHang> entity)
        {
            entity.ToTable("Rpt_TongHopBanHangTheoKhachHang", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AmountDiscount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.AmountNoDiscount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(250);

            entity.Property(e => e.ReturnAmount).HasColumnType("decimal(18, 5)");

            entity.HasOne(d => d.Report)
                .WithMany(p => p.RptTongHopBanHangTheoKhachHang)
                .HasForeignKey(d => d.ReportId)
                .HasConstraintName("FK_Rpt_TongHopBanHangTheoKhachHang_Report");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RptTongHopBanHangTheoKhachHang> entity);
    }
}
