// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RptTinhHinhThucHienHopDongBanConfiguration : IEntityTypeConfiguration<RptTinhHinhThucHienHopDongBan>
    {
        public void Configure(EntityTypeBuilder<RptTinhHinhThucHienHopDongBan> entity)
        {
            entity.ToTable("Rpt_TinhHinhThucHienHopDongBan", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(400);

            entity.Property(e => e.Date).HasColumnType("datetime");

            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductName).HasMaxLength(250);

            entity.Property(e => e.Quantity).HasColumnType("numeric(20, 5)");

            entity.Property(e => e.QuantitySold).HasColumnType("numeric(20, 5)");

            entity.Property(e => e.SaleContract).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.SaleMade).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.HasOne(d => d.Report)
                .WithMany(p => p.RptTinhHinhThucHienHopDongBan)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Rpt_TinhHinhThucHienHopDongBan_Report");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RptTinhHinhThucHienHopDongBan> entity);
    }
}
