// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RptTinhHinhThucHienDonBanHangConfiguration : IEntityTypeConfiguration<RptTinhHinhThucHienDonBanHang>
    {
        public void Configure(EntityTypeBuilder<RptTinhHinhThucHienDonBanHang> entity)
        {
            entity.ToTable("Rpt_TinhHinhThucHienDonBanHang", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(400);

            entity.Property(e => e.OrderCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.OrderDate).HasColumnType("datetime");

            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductName).HasMaxLength(250);

            entity.Property(e => e.Quantity).HasColumnType("numeric(20, 5)");

            entity.Property(e => e.QuantityDelivery).HasColumnType("numeric(20, 5)");

            entity.Property(e => e.SaleMade).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.SaleOrder).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.HasOne(d => d.Report)
                .WithMany(p => p.RptTinhHinhThucHienDonBanHang)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Rpt_TinhHinhThucHienDonBanHang_Report");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RptTinhHinhThucHienDonBanHang> entity);
    }
}
