// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RptTongHopBanHangTheoKhachHangVaDonBanHangConfiguration : IEntityTypeConfiguration<RptTongHopBanHangTheoKhachHangVaDonBanHang>
    {
        public void Configure(EntityTypeBuilder<RptTongHopBanHangTheoKhachHangVaDonBanHang> entity)
        {
            entity.ToTable("Rpt_TongHopBanHangTheoKhachHangVaDonBanHang", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerName).HasMaxLength(250);

            entity.Property(e => e.OrderCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.OrderDate).HasColumnType("datetime");

            entity.Property(e => e.PaymentAmount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.TotalAmountTax).HasColumnType("decimal(18, 5)");

            entity.HasOne(d => d.Report)
                .WithMany(p => p.RptTongHopBanHangTheoKhachHangVaDonBanHang)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Rpt_TongHopBanHangTheoKhachHangVaDonBanHang_Report");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RptTongHopBanHangTheoKhachHangVaDonBanHang> entity);
    }
}
