// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class RptTongHopBanHangTheoMatHangVaKhachHangConfiguration : IEntityTypeConfiguration<RptTongHopBanHangTheoMatHangVaKhachHang>
    {
        public void Configure(EntityTypeBuilder<RptTongHopBanHangTheoMatHangVaKhachHang> entity)
        {
            entity.ToTable("Rpt_TongHopBanHangTheoMatHangVaKhachHang", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AmountDiscount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.AmountNoDiscount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.AmountTax).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Name).HasMaxLength(250);

            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.ReturnAmount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.Revenue).HasColumnType("numeric(20, 5)");

            entity.Property(e => e.SaleAmount).HasColumnType("numeric(20, 5)");

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UnitName).HasMaxLength(250);

            entity.HasOne(d => d.Report)
                .WithMany(p => p.RptTongHopBanHangTheoMatHangVaKhachHang)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Rpt_TongHopBanHangTheoMatHangVaKhachHang_Report");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RptTongHopBanHangTheoMatHangVaKhachHang> entity);
    }
}
