// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class SalesDiscountProductConfiguration : IEntityTypeConfiguration<SalesDiscountProduct>
    {
        public void Configure(EntityTypeBuilder<SalesDiscountProduct> entity)
        {
            entity.ToTable("SalesDiscountProduct", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AmountDiscount).HasColumnType("money");

            entity.Property(e => e.DiscountAmountDistribution).HasColumnType("money");

            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ProductImage).HasMaxLength(250);

            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(300);

            entity.Property(e => e.ReasonDiscount).HasMaxLength(1000);

            entity.Property(e => e.SalesOrderCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Tax).HasMaxLength(150);

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UnitName).HasMaxLength(250);

            entity.Property(e => e.UnitPrice).HasColumnType("money");

            entity.Property(e => e.UnitType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.SalesDiscount)
                .WithMany(p => p.SalesDiscountProduct)
                .HasForeignKey(d => d.SalesDiscountId)
                .HasConstraintName("FK_SalesDiscountProduct_SalesDiscountProduct");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SalesDiscountProduct> entity);
    }
}
