// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class SalesDiscountConfiguration : IEntityTypeConfiguration<SalesDiscount>
    {
        public void Configure(EntityTypeBuilder<SalesDiscount> entity)
        {
            entity.ToTable("SalesDiscount", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.ApproveByName).HasMaxLength(250);

            entity.Property(e => e.ApproveComment).HasMaxLength(1000);

            entity.Property(e => e.ApproveDate).HasColumnType("datetime");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CurrencyName).HasMaxLength(250);

            entity.Property(e => e.CustomerCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CustomerId).HasComment("Khách hàng");

            entity.Property(e => e.CustomerName).HasMaxLength(250);

            entity.Property(e => e.DiscountDate)
                .HasColumnType("datetime")
                .HasComment("Ngày giảm giá");

            entity.Property(e => e.EmployeeCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.EmployeeId).HasComment("Nhân viên");

            entity.Property(e => e.EmployeeName).HasMaxLength(250);

            entity.Property(e => e.ExchangeRate).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.File).HasColumnType("ntext");

            entity.Property(e => e.Note).HasMaxLength(1000);

            entity.Property(e => e.SalesOrderCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("tham chiếu tới bảng order");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.CustomerAddress)
                .WithMany(p => p.SalesDiscount)
                .HasForeignKey(d => d.CustomerAddressId)
                .HasConstraintName("FK_SalesDiscount_CustomerAddress");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.SalesDiscount)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_SalesDiscount_Customer");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SalesDiscount> entity);
    }
}
