// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.SO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.SO.Mappings.Configurations
{
    public partial class StorePriceListConfiguration : IEntityTypeConfiguration<StorePriceList>
    {
        public void Configure(EntityTypeBuilder<StorePriceList> entity)
        {
            entity.ToTable("StorePriceList", "so");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.PriceListName).HasMaxLength(250);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.PriceList)
                .WithMany(p => p.StorePriceList)
                .HasForeignKey(d => d.PriceListId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_StorePriceList_PriceList");

            entity.HasOne(d => d.Store)
                .WithMany(p => p.StorePriceList)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_StorePriceList_Store");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StorePriceList> entity);
    }
}
