// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public  class SP_CREATE_CROSS_ORDERResult
    {
        [Key]
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public decimal? TotalAmountTax { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        
    }
}
