// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_CREATE_INVOICE_PAY_ORDERResult
    {
        public Guid? Id { get; set; }
        public string Code { get; set; }
        public decimal? Total { get; set; }
        public decimal? Paid { get; set; }
        public decimal? Cash { get; set; }
        public decimal? CashHold { get; set; }
        public decimal? CashHoldBid { get; set; }
    }
}
