// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_GET_BID_CREDIT_SETUPResult
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? AccountId { get; set; }
        public bool? BidActive { get; set; }
        public int? BidQuantity { get; set; }
        public int? OrderPending { get; set; }
    }
}
