// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_GET_PRICE_PUCHASE_BY_ACCOUNT_IDResult
    {
        public Guid Id { get; set; }
        public Guid PriceListPurchaseId { get; set; }
        public string PriceListPurchase { get; set; }
        public string PurchaseGroupCode { get; set; }
        public int? BuyFee { get; set; }
        public decimal? BuyFeeMin { get; set; }
        public decimal? BuyFeeFix { get; set; }
        public string Currency { get; set; }
        public decimal? CalculatePrice { get; set; }
    }
}
