// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_GET_ORDEREXPRESS_COUNTERResult
    {
        [Key]
        public int Status { get; set; }
        public int Count { get; set; }
    }
}
