// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_ORDER_UPDATE_DOMESTIC_DELIVERRY_STATUSResult
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public int? Status { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}
