// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_ORDER_STATUS_COUNTERResult
    {
        public int Id { get; set; }
        public int? Status { get; set; }
        public string StatusName { get; set; }
        public int? CountOrder { get; set; }
        public double? Total { get; set; }
    }
}
