// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.SO.Models
{
    public partial class SP_WITHDRAW_WALLETResult
    {
        public Guid Id { get; set; }
        public Guid AccountId { get; set; }
        public string WalletCode { get; set; }
        public decimal? Cash { get; set; }
        public decimal? CashHold { get; set; }
        public decimal? CashHoldBid { get; set; }
        public int? Status { get; set; }
        public string Hash { get; set; }
    }
}
